package com.ccclubs.admin.service.impl;


import com.alibaba.dubbo.config.annotation.Service;
import com.ccclubs.frm.base.CrudService;
import com.ccclubs.admin.orm.mapper.CsVehicleExpMapper;
import com.ccclubs.admin.model.CsVehicleExp;
import com.ccclubs.admin.service.ICsVehicleExpService;

import java.util.List;

/**
 * 异常车辆数据的Service实现
 *
 * @author
 * @create 2018-03-21
 * @category generated by vc-coder
 **/
@Service
public class CsVehicleExpServiceImpl extends CrudService<CsVehicleExpMapper, CsVehicleExp, Long> implements ICsVehicleExpService {

    @Override
    public void insertListSelective(List<CsVehicleExp> list) {
        this.dao.insertListSelective(list);
    }
}