package com.ccclubs.admin.controller.common;

import com.ccclubs.admin.service.IReportService;
import com.ccclubs.admin.vo.VoResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

/**
 * 导出文件相关Controller
 *
 * @author
 * @category generated by NovaV1.0
 * @since V1.0
 */
@RestController
@RequestMapping("/report")
public class ReportController {

    private static final Logger logger = LoggerFactory.getLogger(ReportController.class);
    @Autowired
    IReportService reportService;

    @RequestMapping(value = "/fetch", method = RequestMethod.GET)
    public VoResult<String> getReportFile(String fileUuid) {
        if (reportService.existKey(fileUuid)) {
            String fileName = reportService.getFileUrlByUUID(fileUuid);
            VoResult<String> r = new VoResult<>();
            r.setSuccess(true).setMessage("获取文件地址成功");
            logger.info("report a file success:" + fileName);
            r.setValue("http://" + fileName);
            return r;
        } else {
            VoResult<String> r = new VoResult<>();
            r.setSuccess(true).setMessage("不存在对应的文件，请重新导出。");
            r.setValue(null);
            return r;
        }
    }

}
