package com.ccclubs.quota.orm.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CsState implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_id
     *
     * @mbg.generated
     */
    private Integer cssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_access
     *
     * @mbg.generated
     */
    private Integer cssAccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_host
     *
     * @mbg.generated
     */
    private Integer cssHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_number
     *
     * @mbg.generated
     */
    private String cssNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_car
     *
     * @mbg.generated
     */
    private Integer cssCar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_add_time
     *
     * @mbg.generated
     */
    private Date cssAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_current_time
     *
     * @mbg.generated
     */
    private Date cssCurrentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_rented
     *
     * @mbg.generated
     */
    private String cssRented;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_warn
     *
     * @mbg.generated
     */
    private Integer cssWarn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_rfid
     *
     * @mbg.generated
     */
    private String cssRfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_rfid_dte
     *
     * @mbg.generated
     */
    private String cssRfidDte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_obd_mile
     *
     * @mbg.generated
     */
    private Integer cssObdMile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_engine_t
     *
     * @mbg.generated
     */
    private Integer cssEngineT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_mileage
     *
     * @mbg.generated
     */
    private Integer cssMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_speed
     *
     * @mbg.generated
     */
    private Integer cssSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_motor
     *
     * @mbg.generated
     */
    private Integer cssMotor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_oil
     *
     * @mbg.generated
     */
    private String cssOil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_power
     *
     * @mbg.generated
     */
    private Integer cssPower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_ev_battery
     *
     * @mbg.generated
     */
    private Integer cssEvBattery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_charging
     *
     * @mbg.generated
     */
    private Integer cssCharging;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_fuel_mileage
     *
     * @mbg.generated
     */
    private String cssFuelMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_electric_mileage
     *
     * @mbg.generated
     */
    private String cssElectricMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_endurance
     *
     * @mbg.generated
     */
    private String cssEndurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_temperature
     *
     * @mbg.generated
     */
    private Integer cssTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_csq
     *
     * @mbg.generated
     */
    private Integer cssCsq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_power_consumption
     *
     * @mbg.generated
     */
    private String cssPowerConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_longitude
     *
     * @mbg.generated
     */
    private BigDecimal cssLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_latitude
     *
     * @mbg.generated
     */
    private BigDecimal cssLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_gps_valid
     *
     * @mbg.generated
     */
    private Integer cssGpsValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_gps_cn
     *
     * @mbg.generated
     */
    private Integer cssGpsCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_gps_count
     *
     * @mbg.generated
     */
    private Integer cssGpsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_dir
     *
     * @mbg.generated
     */
    private String cssDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_circular
     *
     * @mbg.generated
     */
    private Integer cssCircular;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_ptc
     *
     * @mbg.generated
     */
    private Integer cssPtc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_compres
     *
     * @mbg.generated
     */
    private Integer cssCompres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_fan
     *
     * @mbg.generated
     */
    private Integer cssFan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_saving
     *
     * @mbg.generated
     */
    private Integer cssSaving;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_door
     *
     * @mbg.generated
     */
    private String cssDoor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_engine
     *
     * @mbg.generated
     */
    private Integer cssEngine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_key
     *
     * @mbg.generated
     */
    private Integer cssKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_gear
     *
     * @mbg.generated
     */
    private Integer cssGear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_light
     *
     * @mbg.generated
     */
    private Integer cssLight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_lock
     *
     * @mbg.generated
     */
    private Integer cssLock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_net_type
     *
     * @mbg.generated
     */
    private Integer cssNetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_base_lac
     *
     * @mbg.generated
     */
    private Integer cssBaseLac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_base_ci
     *
     * @mbg.generated
     */
    private Integer cssBaseCi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_order
     *
     * @mbg.generated
     */
    private Long cssOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_state.css_mo_data
     *
     * @mbg.generated
     */
    private String cssMoData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_state
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_id
     *
     * @return the value of cs_state.css_id
     *
     * @mbg.generated
     */
    public Integer getCssId() {
        return cssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_id
     *
     * @param cssId the value for cs_state.css_id
     *
     * @mbg.generated
     */
    public void setCssId(Integer cssId) {
        this.cssId = cssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_access
     *
     * @return the value of cs_state.css_access
     *
     * @mbg.generated
     */
    public Integer getCssAccess() {
        return cssAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_access
     *
     * @param cssAccess the value for cs_state.css_access
     *
     * @mbg.generated
     */
    public void setCssAccess(Integer cssAccess) {
        this.cssAccess = cssAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_host
     *
     * @return the value of cs_state.css_host
     *
     * @mbg.generated
     */
    public Integer getCssHost() {
        return cssHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_host
     *
     * @param cssHost the value for cs_state.css_host
     *
     * @mbg.generated
     */
    public void setCssHost(Integer cssHost) {
        this.cssHost = cssHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_number
     *
     * @return the value of cs_state.css_number
     *
     * @mbg.generated
     */
    public String getCssNumber() {
        return cssNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_number
     *
     * @param cssNumber the value for cs_state.css_number
     *
     * @mbg.generated
     */
    public void setCssNumber(String cssNumber) {
        this.cssNumber = cssNumber == null ? null : cssNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_car
     *
     * @return the value of cs_state.css_car
     *
     * @mbg.generated
     */
    public Integer getCssCar() {
        return cssCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_car
     *
     * @param cssCar the value for cs_state.css_car
     *
     * @mbg.generated
     */
    public void setCssCar(Integer cssCar) {
        this.cssCar = cssCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_add_time
     *
     * @return the value of cs_state.css_add_time
     *
     * @mbg.generated
     */
    public Date getCssAddTime() {
        return cssAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_add_time
     *
     * @param cssAddTime the value for cs_state.css_add_time
     *
     * @mbg.generated
     */
    public void setCssAddTime(Date cssAddTime) {
        this.cssAddTime = cssAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_current_time
     *
     * @return the value of cs_state.css_current_time
     *
     * @mbg.generated
     */
    public Date getCssCurrentTime() {
        return cssCurrentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_current_time
     *
     * @param cssCurrentTime the value for cs_state.css_current_time
     *
     * @mbg.generated
     */
    public void setCssCurrentTime(Date cssCurrentTime) {
        this.cssCurrentTime = cssCurrentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_rented
     *
     * @return the value of cs_state.css_rented
     *
     * @mbg.generated
     */
    public String getCssRented() {
        return cssRented;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_rented
     *
     * @param cssRented the value for cs_state.css_rented
     *
     * @mbg.generated
     */
    public void setCssRented(String cssRented) {
        this.cssRented = cssRented == null ? null : cssRented.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_warn
     *
     * @return the value of cs_state.css_warn
     *
     * @mbg.generated
     */
    public Integer getCssWarn() {
        return cssWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_warn
     *
     * @param cssWarn the value for cs_state.css_warn
     *
     * @mbg.generated
     */
    public void setCssWarn(Integer cssWarn) {
        this.cssWarn = cssWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_rfid
     *
     * @return the value of cs_state.css_rfid
     *
     * @mbg.generated
     */
    public String getCssRfid() {
        return cssRfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_rfid
     *
     * @param cssRfid the value for cs_state.css_rfid
     *
     * @mbg.generated
     */
    public void setCssRfid(String cssRfid) {
        this.cssRfid = cssRfid == null ? null : cssRfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_rfid_dte
     *
     * @return the value of cs_state.css_rfid_dte
     *
     * @mbg.generated
     */
    public String getCssRfidDte() {
        return cssRfidDte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_rfid_dte
     *
     * @param cssRfidDte the value for cs_state.css_rfid_dte
     *
     * @mbg.generated
     */
    public void setCssRfidDte(String cssRfidDte) {
        this.cssRfidDte = cssRfidDte == null ? null : cssRfidDte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_obd_mile
     *
     * @return the value of cs_state.css_obd_mile
     *
     * @mbg.generated
     */
    public Integer getCssObdMile() {
        return cssObdMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_obd_mile
     *
     * @param cssObdMile the value for cs_state.css_obd_mile
     *
     * @mbg.generated
     */
    public void setCssObdMile(Integer cssObdMile) {
        this.cssObdMile = cssObdMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_engine_t
     *
     * @return the value of cs_state.css_engine_t
     *
     * @mbg.generated
     */
    public Integer getCssEngineT() {
        return cssEngineT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_engine_t
     *
     * @param cssEngineT the value for cs_state.css_engine_t
     *
     * @mbg.generated
     */
    public void setCssEngineT(Integer cssEngineT) {
        this.cssEngineT = cssEngineT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_mileage
     *
     * @return the value of cs_state.css_mileage
     *
     * @mbg.generated
     */
    public Integer getCssMileage() {
        return cssMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_mileage
     *
     * @param cssMileage the value for cs_state.css_mileage
     *
     * @mbg.generated
     */
    public void setCssMileage(Integer cssMileage) {
        this.cssMileage = cssMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_speed
     *
     * @return the value of cs_state.css_speed
     *
     * @mbg.generated
     */
    public Integer getCssSpeed() {
        return cssSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_speed
     *
     * @param cssSpeed the value for cs_state.css_speed
     *
     * @mbg.generated
     */
    public void setCssSpeed(Integer cssSpeed) {
        this.cssSpeed = cssSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_motor
     *
     * @return the value of cs_state.css_motor
     *
     * @mbg.generated
     */
    public Integer getCssMotor() {
        return cssMotor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_motor
     *
     * @param cssMotor the value for cs_state.css_motor
     *
     * @mbg.generated
     */
    public void setCssMotor(Integer cssMotor) {
        this.cssMotor = cssMotor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_oil
     *
     * @return the value of cs_state.css_oil
     *
     * @mbg.generated
     */
    public String getCssOil() {
        return cssOil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_oil
     *
     * @param cssOil the value for cs_state.css_oil
     *
     * @mbg.generated
     */
    public void setCssOil(String cssOil) {
        this.cssOil = cssOil == null ? null : cssOil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_power
     *
     * @return the value of cs_state.css_power
     *
     * @mbg.generated
     */
    public Integer getCssPower() {
        return cssPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_power
     *
     * @param cssPower the value for cs_state.css_power
     *
     * @mbg.generated
     */
    public void setCssPower(Integer cssPower) {
        this.cssPower = cssPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_ev_battery
     *
     * @return the value of cs_state.css_ev_battery
     *
     * @mbg.generated
     */
    public Integer getCssEvBattery() {
        return cssEvBattery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_ev_battery
     *
     * @param cssEvBattery the value for cs_state.css_ev_battery
     *
     * @mbg.generated
     */
    public void setCssEvBattery(Integer cssEvBattery) {
        this.cssEvBattery = cssEvBattery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_charging
     *
     * @return the value of cs_state.css_charging
     *
     * @mbg.generated
     */
    public Integer getCssCharging() {
        return cssCharging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_charging
     *
     * @param cssCharging the value for cs_state.css_charging
     *
     * @mbg.generated
     */
    public void setCssCharging(Integer cssCharging) {
        this.cssCharging = cssCharging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_fuel_mileage
     *
     * @return the value of cs_state.css_fuel_mileage
     *
     * @mbg.generated
     */
    public String getCssFuelMileage() {
        return cssFuelMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_fuel_mileage
     *
     * @param cssFuelMileage the value for cs_state.css_fuel_mileage
     *
     * @mbg.generated
     */
    public void setCssFuelMileage(String cssFuelMileage) {
        this.cssFuelMileage = cssFuelMileage == null ? null : cssFuelMileage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_electric_mileage
     *
     * @return the value of cs_state.css_electric_mileage
     *
     * @mbg.generated
     */
    public String getCssElectricMileage() {
        return cssElectricMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_electric_mileage
     *
     * @param cssElectricMileage the value for cs_state.css_electric_mileage
     *
     * @mbg.generated
     */
    public void setCssElectricMileage(String cssElectricMileage) {
        this.cssElectricMileage = cssElectricMileage == null ? null : cssElectricMileage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_endurance
     *
     * @return the value of cs_state.css_endurance
     *
     * @mbg.generated
     */
    public String getCssEndurance() {
        return cssEndurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_endurance
     *
     * @param cssEndurance the value for cs_state.css_endurance
     *
     * @mbg.generated
     */
    public void setCssEndurance(String cssEndurance) {
        this.cssEndurance = cssEndurance == null ? null : cssEndurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_temperature
     *
     * @return the value of cs_state.css_temperature
     *
     * @mbg.generated
     */
    public Integer getCssTemperature() {
        return cssTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_temperature
     *
     * @param cssTemperature the value for cs_state.css_temperature
     *
     * @mbg.generated
     */
    public void setCssTemperature(Integer cssTemperature) {
        this.cssTemperature = cssTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_csq
     *
     * @return the value of cs_state.css_csq
     *
     * @mbg.generated
     */
    public Integer getCssCsq() {
        return cssCsq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_csq
     *
     * @param cssCsq the value for cs_state.css_csq
     *
     * @mbg.generated
     */
    public void setCssCsq(Integer cssCsq) {
        this.cssCsq = cssCsq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_power_consumption
     *
     * @return the value of cs_state.css_power_consumption
     *
     * @mbg.generated
     */
    public String getCssPowerConsumption() {
        return cssPowerConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_power_consumption
     *
     * @param cssPowerConsumption the value for cs_state.css_power_consumption
     *
     * @mbg.generated
     */
    public void setCssPowerConsumption(String cssPowerConsumption) {
        this.cssPowerConsumption = cssPowerConsumption == null ? null : cssPowerConsumption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_longitude
     *
     * @return the value of cs_state.css_longitude
     *
     * @mbg.generated
     */
    public BigDecimal getCssLongitude() {
        return cssLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_longitude
     *
     * @param cssLongitude the value for cs_state.css_longitude
     *
     * @mbg.generated
     */
    public void setCssLongitude(BigDecimal cssLongitude) {
        this.cssLongitude = cssLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_latitude
     *
     * @return the value of cs_state.css_latitude
     *
     * @mbg.generated
     */
    public BigDecimal getCssLatitude() {
        return cssLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_latitude
     *
     * @param cssLatitude the value for cs_state.css_latitude
     *
     * @mbg.generated
     */
    public void setCssLatitude(BigDecimal cssLatitude) {
        this.cssLatitude = cssLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_gps_valid
     *
     * @return the value of cs_state.css_gps_valid
     *
     * @mbg.generated
     */
    public Integer getCssGpsValid() {
        return cssGpsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_gps_valid
     *
     * @param cssGpsValid the value for cs_state.css_gps_valid
     *
     * @mbg.generated
     */
    public void setCssGpsValid(Integer cssGpsValid) {
        this.cssGpsValid = cssGpsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_gps_cn
     *
     * @return the value of cs_state.css_gps_cn
     *
     * @mbg.generated
     */
    public Integer getCssGpsCn() {
        return cssGpsCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_gps_cn
     *
     * @param cssGpsCn the value for cs_state.css_gps_cn
     *
     * @mbg.generated
     */
    public void setCssGpsCn(Integer cssGpsCn) {
        this.cssGpsCn = cssGpsCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_gps_count
     *
     * @return the value of cs_state.css_gps_count
     *
     * @mbg.generated
     */
    public Integer getCssGpsCount() {
        return cssGpsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_gps_count
     *
     * @param cssGpsCount the value for cs_state.css_gps_count
     *
     * @mbg.generated
     */
    public void setCssGpsCount(Integer cssGpsCount) {
        this.cssGpsCount = cssGpsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_dir
     *
     * @return the value of cs_state.css_dir
     *
     * @mbg.generated
     */
    public String getCssDir() {
        return cssDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_dir
     *
     * @param cssDir the value for cs_state.css_dir
     *
     * @mbg.generated
     */
    public void setCssDir(String cssDir) {
        this.cssDir = cssDir == null ? null : cssDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_circular
     *
     * @return the value of cs_state.css_circular
     *
     * @mbg.generated
     */
    public Integer getCssCircular() {
        return cssCircular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_circular
     *
     * @param cssCircular the value for cs_state.css_circular
     *
     * @mbg.generated
     */
    public void setCssCircular(Integer cssCircular) {
        this.cssCircular = cssCircular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_ptc
     *
     * @return the value of cs_state.css_ptc
     *
     * @mbg.generated
     */
    public Integer getCssPtc() {
        return cssPtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_ptc
     *
     * @param cssPtc the value for cs_state.css_ptc
     *
     * @mbg.generated
     */
    public void setCssPtc(Integer cssPtc) {
        this.cssPtc = cssPtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_compres
     *
     * @return the value of cs_state.css_compres
     *
     * @mbg.generated
     */
    public Integer getCssCompres() {
        return cssCompres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_compres
     *
     * @param cssCompres the value for cs_state.css_compres
     *
     * @mbg.generated
     */
    public void setCssCompres(Integer cssCompres) {
        this.cssCompres = cssCompres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_fan
     *
     * @return the value of cs_state.css_fan
     *
     * @mbg.generated
     */
    public Integer getCssFan() {
        return cssFan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_fan
     *
     * @param cssFan the value for cs_state.css_fan
     *
     * @mbg.generated
     */
    public void setCssFan(Integer cssFan) {
        this.cssFan = cssFan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_saving
     *
     * @return the value of cs_state.css_saving
     *
     * @mbg.generated
     */
    public Integer getCssSaving() {
        return cssSaving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_saving
     *
     * @param cssSaving the value for cs_state.css_saving
     *
     * @mbg.generated
     */
    public void setCssSaving(Integer cssSaving) {
        this.cssSaving = cssSaving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_door
     *
     * @return the value of cs_state.css_door
     *
     * @mbg.generated
     */
    public String getCssDoor() {
        return cssDoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_door
     *
     * @param cssDoor the value for cs_state.css_door
     *
     * @mbg.generated
     */
    public void setCssDoor(String cssDoor) {
        this.cssDoor = cssDoor == null ? null : cssDoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_engine
     *
     * @return the value of cs_state.css_engine
     *
     * @mbg.generated
     */
    public Integer getCssEngine() {
        return cssEngine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_engine
     *
     * @param cssEngine the value for cs_state.css_engine
     *
     * @mbg.generated
     */
    public void setCssEngine(Integer cssEngine) {
        this.cssEngine = cssEngine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_key
     *
     * @return the value of cs_state.css_key
     *
     * @mbg.generated
     */
    public Integer getCssKey() {
        return cssKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_key
     *
     * @param cssKey the value for cs_state.css_key
     *
     * @mbg.generated
     */
    public void setCssKey(Integer cssKey) {
        this.cssKey = cssKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_gear
     *
     * @return the value of cs_state.css_gear
     *
     * @mbg.generated
     */
    public Integer getCssGear() {
        return cssGear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_gear
     *
     * @param cssGear the value for cs_state.css_gear
     *
     * @mbg.generated
     */
    public void setCssGear(Integer cssGear) {
        this.cssGear = cssGear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_light
     *
     * @return the value of cs_state.css_light
     *
     * @mbg.generated
     */
    public Integer getCssLight() {
        return cssLight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_light
     *
     * @param cssLight the value for cs_state.css_light
     *
     * @mbg.generated
     */
    public void setCssLight(Integer cssLight) {
        this.cssLight = cssLight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_lock
     *
     * @return the value of cs_state.css_lock
     *
     * @mbg.generated
     */
    public Integer getCssLock() {
        return cssLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_lock
     *
     * @param cssLock the value for cs_state.css_lock
     *
     * @mbg.generated
     */
    public void setCssLock(Integer cssLock) {
        this.cssLock = cssLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_net_type
     *
     * @return the value of cs_state.css_net_type
     *
     * @mbg.generated
     */
    public Integer getCssNetType() {
        return cssNetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_net_type
     *
     * @param cssNetType the value for cs_state.css_net_type
     *
     * @mbg.generated
     */
    public void setCssNetType(Integer cssNetType) {
        this.cssNetType = cssNetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_base_lac
     *
     * @return the value of cs_state.css_base_lac
     *
     * @mbg.generated
     */
    public Integer getCssBaseLac() {
        return cssBaseLac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_base_lac
     *
     * @param cssBaseLac the value for cs_state.css_base_lac
     *
     * @mbg.generated
     */
    public void setCssBaseLac(Integer cssBaseLac) {
        this.cssBaseLac = cssBaseLac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_base_ci
     *
     * @return the value of cs_state.css_base_ci
     *
     * @mbg.generated
     */
    public Integer getCssBaseCi() {
        return cssBaseCi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_base_ci
     *
     * @param cssBaseCi the value for cs_state.css_base_ci
     *
     * @mbg.generated
     */
    public void setCssBaseCi(Integer cssBaseCi) {
        this.cssBaseCi = cssBaseCi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_order
     *
     * @return the value of cs_state.css_order
     *
     * @mbg.generated
     */
    public Long getCssOrder() {
        return cssOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_order
     *
     * @param cssOrder the value for cs_state.css_order
     *
     * @mbg.generated
     */
    public void setCssOrder(Long cssOrder) {
        this.cssOrder = cssOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_state.css_mo_data
     *
     * @return the value of cs_state.css_mo_data
     *
     * @mbg.generated
     */
    public String getCssMoData() {
        return cssMoData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_state.css_mo_data
     *
     * @param cssMoData the value for cs_state.css_mo_data
     *
     * @mbg.generated
     */
    public void setCssMoData(String cssMoData) {
        this.cssMoData = cssMoData == null ? null : cssMoData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_state
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CsState other = (CsState) that;
        return (this.getCssId() == null ? other.getCssId() == null : this.getCssId().equals(other.getCssId()))
            && (this.getCssAccess() == null ? other.getCssAccess() == null : this.getCssAccess().equals(other.getCssAccess()))
            && (this.getCssHost() == null ? other.getCssHost() == null : this.getCssHost().equals(other.getCssHost()))
            && (this.getCssNumber() == null ? other.getCssNumber() == null : this.getCssNumber().equals(other.getCssNumber()))
            && (this.getCssCar() == null ? other.getCssCar() == null : this.getCssCar().equals(other.getCssCar()))
            && (this.getCssAddTime() == null ? other.getCssAddTime() == null : this.getCssAddTime().equals(other.getCssAddTime()))
            && (this.getCssCurrentTime() == null ? other.getCssCurrentTime() == null : this.getCssCurrentTime().equals(other.getCssCurrentTime()))
            && (this.getCssRented() == null ? other.getCssRented() == null : this.getCssRented().equals(other.getCssRented()))
            && (this.getCssWarn() == null ? other.getCssWarn() == null : this.getCssWarn().equals(other.getCssWarn()))
            && (this.getCssRfid() == null ? other.getCssRfid() == null : this.getCssRfid().equals(other.getCssRfid()))
            && (this.getCssRfidDte() == null ? other.getCssRfidDte() == null : this.getCssRfidDte().equals(other.getCssRfidDte()))
            && (this.getCssObdMile() == null ? other.getCssObdMile() == null : this.getCssObdMile().equals(other.getCssObdMile()))
            && (this.getCssEngineT() == null ? other.getCssEngineT() == null : this.getCssEngineT().equals(other.getCssEngineT()))
            && (this.getCssMileage() == null ? other.getCssMileage() == null : this.getCssMileage().equals(other.getCssMileage()))
            && (this.getCssSpeed() == null ? other.getCssSpeed() == null : this.getCssSpeed().equals(other.getCssSpeed()))
            && (this.getCssMotor() == null ? other.getCssMotor() == null : this.getCssMotor().equals(other.getCssMotor()))
            && (this.getCssOil() == null ? other.getCssOil() == null : this.getCssOil().equals(other.getCssOil()))
            && (this.getCssPower() == null ? other.getCssPower() == null : this.getCssPower().equals(other.getCssPower()))
            && (this.getCssEvBattery() == null ? other.getCssEvBattery() == null : this.getCssEvBattery().equals(other.getCssEvBattery()))
            && (this.getCssCharging() == null ? other.getCssCharging() == null : this.getCssCharging().equals(other.getCssCharging()))
            && (this.getCssFuelMileage() == null ? other.getCssFuelMileage() == null : this.getCssFuelMileage().equals(other.getCssFuelMileage()))
            && (this.getCssElectricMileage() == null ? other.getCssElectricMileage() == null : this.getCssElectricMileage().equals(other.getCssElectricMileage()))
            && (this.getCssEndurance() == null ? other.getCssEndurance() == null : this.getCssEndurance().equals(other.getCssEndurance()))
            && (this.getCssTemperature() == null ? other.getCssTemperature() == null : this.getCssTemperature().equals(other.getCssTemperature()))
            && (this.getCssCsq() == null ? other.getCssCsq() == null : this.getCssCsq().equals(other.getCssCsq()))
            && (this.getCssPowerConsumption() == null ? other.getCssPowerConsumption() == null : this.getCssPowerConsumption().equals(other.getCssPowerConsumption()))
            && (this.getCssLongitude() == null ? other.getCssLongitude() == null : this.getCssLongitude().equals(other.getCssLongitude()))
            && (this.getCssLatitude() == null ? other.getCssLatitude() == null : this.getCssLatitude().equals(other.getCssLatitude()))
            && (this.getCssGpsValid() == null ? other.getCssGpsValid() == null : this.getCssGpsValid().equals(other.getCssGpsValid()))
            && (this.getCssGpsCn() == null ? other.getCssGpsCn() == null : this.getCssGpsCn().equals(other.getCssGpsCn()))
            && (this.getCssGpsCount() == null ? other.getCssGpsCount() == null : this.getCssGpsCount().equals(other.getCssGpsCount()))
            && (this.getCssDir() == null ? other.getCssDir() == null : this.getCssDir().equals(other.getCssDir()))
            && (this.getCssCircular() == null ? other.getCssCircular() == null : this.getCssCircular().equals(other.getCssCircular()))
            && (this.getCssPtc() == null ? other.getCssPtc() == null : this.getCssPtc().equals(other.getCssPtc()))
            && (this.getCssCompres() == null ? other.getCssCompres() == null : this.getCssCompres().equals(other.getCssCompres()))
            && (this.getCssFan() == null ? other.getCssFan() == null : this.getCssFan().equals(other.getCssFan()))
            && (this.getCssSaving() == null ? other.getCssSaving() == null : this.getCssSaving().equals(other.getCssSaving()))
            && (this.getCssDoor() == null ? other.getCssDoor() == null : this.getCssDoor().equals(other.getCssDoor()))
            && (this.getCssEngine() == null ? other.getCssEngine() == null : this.getCssEngine().equals(other.getCssEngine()))
            && (this.getCssKey() == null ? other.getCssKey() == null : this.getCssKey().equals(other.getCssKey()))
            && (this.getCssGear() == null ? other.getCssGear() == null : this.getCssGear().equals(other.getCssGear()))
            && (this.getCssLight() == null ? other.getCssLight() == null : this.getCssLight().equals(other.getCssLight()))
            && (this.getCssLock() == null ? other.getCssLock() == null : this.getCssLock().equals(other.getCssLock()))
            && (this.getCssNetType() == null ? other.getCssNetType() == null : this.getCssNetType().equals(other.getCssNetType()))
            && (this.getCssBaseLac() == null ? other.getCssBaseLac() == null : this.getCssBaseLac().equals(other.getCssBaseLac()))
            && (this.getCssBaseCi() == null ? other.getCssBaseCi() == null : this.getCssBaseCi().equals(other.getCssBaseCi()))
            && (this.getCssOrder() == null ? other.getCssOrder() == null : this.getCssOrder().equals(other.getCssOrder()))
            && (this.getCssMoData() == null ? other.getCssMoData() == null : this.getCssMoData().equals(other.getCssMoData()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_state
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCssId() == null) ? 0 : getCssId().hashCode());
        result = prime * result + ((getCssAccess() == null) ? 0 : getCssAccess().hashCode());
        result = prime * result + ((getCssHost() == null) ? 0 : getCssHost().hashCode());
        result = prime * result + ((getCssNumber() == null) ? 0 : getCssNumber().hashCode());
        result = prime * result + ((getCssCar() == null) ? 0 : getCssCar().hashCode());
        result = prime * result + ((getCssAddTime() == null) ? 0 : getCssAddTime().hashCode());
        result = prime * result + ((getCssCurrentTime() == null) ? 0 : getCssCurrentTime().hashCode());
        result = prime * result + ((getCssRented() == null) ? 0 : getCssRented().hashCode());
        result = prime * result + ((getCssWarn() == null) ? 0 : getCssWarn().hashCode());
        result = prime * result + ((getCssRfid() == null) ? 0 : getCssRfid().hashCode());
        result = prime * result + ((getCssRfidDte() == null) ? 0 : getCssRfidDte().hashCode());
        result = prime * result + ((getCssObdMile() == null) ? 0 : getCssObdMile().hashCode());
        result = prime * result + ((getCssEngineT() == null) ? 0 : getCssEngineT().hashCode());
        result = prime * result + ((getCssMileage() == null) ? 0 : getCssMileage().hashCode());
        result = prime * result + ((getCssSpeed() == null) ? 0 : getCssSpeed().hashCode());
        result = prime * result + ((getCssMotor() == null) ? 0 : getCssMotor().hashCode());
        result = prime * result + ((getCssOil() == null) ? 0 : getCssOil().hashCode());
        result = prime * result + ((getCssPower() == null) ? 0 : getCssPower().hashCode());
        result = prime * result + ((getCssEvBattery() == null) ? 0 : getCssEvBattery().hashCode());
        result = prime * result + ((getCssCharging() == null) ? 0 : getCssCharging().hashCode());
        result = prime * result + ((getCssFuelMileage() == null) ? 0 : getCssFuelMileage().hashCode());
        result = prime * result + ((getCssElectricMileage() == null) ? 0 : getCssElectricMileage().hashCode());
        result = prime * result + ((getCssEndurance() == null) ? 0 : getCssEndurance().hashCode());
        result = prime * result + ((getCssTemperature() == null) ? 0 : getCssTemperature().hashCode());
        result = prime * result + ((getCssCsq() == null) ? 0 : getCssCsq().hashCode());
        result = prime * result + ((getCssPowerConsumption() == null) ? 0 : getCssPowerConsumption().hashCode());
        result = prime * result + ((getCssLongitude() == null) ? 0 : getCssLongitude().hashCode());
        result = prime * result + ((getCssLatitude() == null) ? 0 : getCssLatitude().hashCode());
        result = prime * result + ((getCssGpsValid() == null) ? 0 : getCssGpsValid().hashCode());
        result = prime * result + ((getCssGpsCn() == null) ? 0 : getCssGpsCn().hashCode());
        result = prime * result + ((getCssGpsCount() == null) ? 0 : getCssGpsCount().hashCode());
        result = prime * result + ((getCssDir() == null) ? 0 : getCssDir().hashCode());
        result = prime * result + ((getCssCircular() == null) ? 0 : getCssCircular().hashCode());
        result = prime * result + ((getCssPtc() == null) ? 0 : getCssPtc().hashCode());
        result = prime * result + ((getCssCompres() == null) ? 0 : getCssCompres().hashCode());
        result = prime * result + ((getCssFan() == null) ? 0 : getCssFan().hashCode());
        result = prime * result + ((getCssSaving() == null) ? 0 : getCssSaving().hashCode());
        result = prime * result + ((getCssDoor() == null) ? 0 : getCssDoor().hashCode());
        result = prime * result + ((getCssEngine() == null) ? 0 : getCssEngine().hashCode());
        result = prime * result + ((getCssKey() == null) ? 0 : getCssKey().hashCode());
        result = prime * result + ((getCssGear() == null) ? 0 : getCssGear().hashCode());
        result = prime * result + ((getCssLight() == null) ? 0 : getCssLight().hashCode());
        result = prime * result + ((getCssLock() == null) ? 0 : getCssLock().hashCode());
        result = prime * result + ((getCssNetType() == null) ? 0 : getCssNetType().hashCode());
        result = prime * result + ((getCssBaseLac() == null) ? 0 : getCssBaseLac().hashCode());
        result = prime * result + ((getCssBaseCi() == null) ? 0 : getCssBaseCi().hashCode());
        result = prime * result + ((getCssOrder() == null) ? 0 : getCssOrder().hashCode());
        result = prime * result + ((getCssMoData() == null) ? 0 : getCssMoData().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_state
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cssId=").append(cssId);
        sb.append(", cssAccess=").append(cssAccess);
        sb.append(", cssHost=").append(cssHost);
        sb.append(", cssNumber=").append(cssNumber);
        sb.append(", cssCar=").append(cssCar);
        sb.append(", cssAddTime=").append(cssAddTime);
        sb.append(", cssCurrentTime=").append(cssCurrentTime);
        sb.append(", cssRented=").append(cssRented);
        sb.append(", cssWarn=").append(cssWarn);
        sb.append(", cssRfid=").append(cssRfid);
        sb.append(", cssRfidDte=").append(cssRfidDte);
        sb.append(", cssObdMile=").append(cssObdMile);
        sb.append(", cssEngineT=").append(cssEngineT);
        sb.append(", cssMileage=").append(cssMileage);
        sb.append(", cssSpeed=").append(cssSpeed);
        sb.append(", cssMotor=").append(cssMotor);
        sb.append(", cssOil=").append(cssOil);
        sb.append(", cssPower=").append(cssPower);
        sb.append(", cssEvBattery=").append(cssEvBattery);
        sb.append(", cssCharging=").append(cssCharging);
        sb.append(", cssFuelMileage=").append(cssFuelMileage);
        sb.append(", cssElectricMileage=").append(cssElectricMileage);
        sb.append(", cssEndurance=").append(cssEndurance);
        sb.append(", cssTemperature=").append(cssTemperature);
        sb.append(", cssCsq=").append(cssCsq);
        sb.append(", cssPowerConsumption=").append(cssPowerConsumption);
        sb.append(", cssLongitude=").append(cssLongitude);
        sb.append(", cssLatitude=").append(cssLatitude);
        sb.append(", cssGpsValid=").append(cssGpsValid);
        sb.append(", cssGpsCn=").append(cssGpsCn);
        sb.append(", cssGpsCount=").append(cssGpsCount);
        sb.append(", cssDir=").append(cssDir);
        sb.append(", cssCircular=").append(cssCircular);
        sb.append(", cssPtc=").append(cssPtc);
        sb.append(", cssCompres=").append(cssCompres);
        sb.append(", cssFan=").append(cssFan);
        sb.append(", cssSaving=").append(cssSaving);
        sb.append(", cssDoor=").append(cssDoor);
        sb.append(", cssEngine=").append(cssEngine);
        sb.append(", cssKey=").append(cssKey);
        sb.append(", cssGear=").append(cssGear);
        sb.append(", cssLight=").append(cssLight);
        sb.append(", cssLock=").append(cssLock);
        sb.append(", cssNetType=").append(cssNetType);
        sb.append(", cssBaseLac=").append(cssBaseLac);
        sb.append(", cssBaseCi=").append(cssBaseCi);
        sb.append(", cssOrder=").append(cssOrder);
        sb.append(", cssMoData=").append(cssMoData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}