package com.ccclubs.quota.orm.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CsVehicleMachineRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_id
     *
     * @mbg.generated
     */
    private Long csId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_vender
     *
     * @mbg.generated
     */
    private String csVender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_vin
     *
     * @mbg.generated
     */
    private String csVin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_te_no
     *
     * @mbg.generated
     */
    private String csTeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_number
     *
     * @mbg.generated
     */
    private String csNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_te_type
     *
     * @mbg.generated
     */
    private String csTeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_car_no
     *
     * @mbg.generated
     */
    private String csCarNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_car_type
     *
     * @mbg.generated
     */
    private String csCarType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.cs_battery_capacity
     *
     * @mbg.generated
     */
    private BigDecimal csBatteryCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_vehicle_machine_rel.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_id
     *
     * @return the value of cs_vehicle_machine_rel.cs_id
     *
     * @mbg.generated
     */
    public Long getCsId() {
        return csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_id
     *
     * @param csId the value for cs_vehicle_machine_rel.cs_id
     *
     * @mbg.generated
     */
    public void setCsId(Long csId) {
        this.csId = csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_vender
     *
     * @return the value of cs_vehicle_machine_rel.cs_vender
     *
     * @mbg.generated
     */
    public String getCsVender() {
        return csVender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_vender
     *
     * @param csVender the value for cs_vehicle_machine_rel.cs_vender
     *
     * @mbg.generated
     */
    public void setCsVender(String csVender) {
        this.csVender = csVender == null ? null : csVender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_vin
     *
     * @return the value of cs_vehicle_machine_rel.cs_vin
     *
     * @mbg.generated
     */
    public String getCsVin() {
        return csVin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_vin
     *
     * @param csVin the value for cs_vehicle_machine_rel.cs_vin
     *
     * @mbg.generated
     */
    public void setCsVin(String csVin) {
        this.csVin = csVin == null ? null : csVin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_te_no
     *
     * @return the value of cs_vehicle_machine_rel.cs_te_no
     *
     * @mbg.generated
     */
    public String getCsTeNo() {
        return csTeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_te_no
     *
     * @param csTeNo the value for cs_vehicle_machine_rel.cs_te_no
     *
     * @mbg.generated
     */
    public void setCsTeNo(String csTeNo) {
        this.csTeNo = csTeNo == null ? null : csTeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_number
     *
     * @return the value of cs_vehicle_machine_rel.cs_number
     *
     * @mbg.generated
     */
    public String getCsNumber() {
        return csNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_number
     *
     * @param csNumber the value for cs_vehicle_machine_rel.cs_number
     *
     * @mbg.generated
     */
    public void setCsNumber(String csNumber) {
        this.csNumber = csNumber == null ? null : csNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_te_type
     *
     * @return the value of cs_vehicle_machine_rel.cs_te_type
     *
     * @mbg.generated
     */
    public String getCsTeType() {
        return csTeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_te_type
     *
     * @param csTeType the value for cs_vehicle_machine_rel.cs_te_type
     *
     * @mbg.generated
     */
    public void setCsTeType(String csTeType) {
        this.csTeType = csTeType == null ? null : csTeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_car_no
     *
     * @return the value of cs_vehicle_machine_rel.cs_car_no
     *
     * @mbg.generated
     */
    public String getCsCarNo() {
        return csCarNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_car_no
     *
     * @param csCarNo the value for cs_vehicle_machine_rel.cs_car_no
     *
     * @mbg.generated
     */
    public void setCsCarNo(String csCarNo) {
        this.csCarNo = csCarNo == null ? null : csCarNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_car_type
     *
     * @return the value of cs_vehicle_machine_rel.cs_car_type
     *
     * @mbg.generated
     */
    public String getCsCarType() {
        return csCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_car_type
     *
     * @param csCarType the value for cs_vehicle_machine_rel.cs_car_type
     *
     * @mbg.generated
     */
    public void setCsCarType(String csCarType) {
        this.csCarType = csCarType == null ? null : csCarType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.cs_battery_capacity
     *
     * @return the value of cs_vehicle_machine_rel.cs_battery_capacity
     *
     * @mbg.generated
     */
    public BigDecimal getCsBatteryCapacity() {
        return csBatteryCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.cs_battery_capacity
     *
     * @param csBatteryCapacity the value for cs_vehicle_machine_rel.cs_battery_capacity
     *
     * @mbg.generated
     */
    public void setCsBatteryCapacity(BigDecimal csBatteryCapacity) {
        this.csBatteryCapacity = csBatteryCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.createTime
     *
     * @return the value of cs_vehicle_machine_rel.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.createTime
     *
     * @param createtime the value for cs_vehicle_machine_rel.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_vehicle_machine_rel.updateTime
     *
     * @return the value of cs_vehicle_machine_rel.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_vehicle_machine_rel.updateTime
     *
     * @param updatetime the value for cs_vehicle_machine_rel.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CsVehicleMachineRel other = (CsVehicleMachineRel) that;
        return (this.getCsId() == null ? other.getCsId() == null : this.getCsId().equals(other.getCsId()))
            && (this.getCsVender() == null ? other.getCsVender() == null : this.getCsVender().equals(other.getCsVender()))
            && (this.getCsVin() == null ? other.getCsVin() == null : this.getCsVin().equals(other.getCsVin()))
            && (this.getCsTeNo() == null ? other.getCsTeNo() == null : this.getCsTeNo().equals(other.getCsTeNo()))
            && (this.getCsNumber() == null ? other.getCsNumber() == null : this.getCsNumber().equals(other.getCsNumber()))
            && (this.getCsTeType() == null ? other.getCsTeType() == null : this.getCsTeType().equals(other.getCsTeType()))
            && (this.getCsCarNo() == null ? other.getCsCarNo() == null : this.getCsCarNo().equals(other.getCsCarNo()))
            && (this.getCsCarType() == null ? other.getCsCarType() == null : this.getCsCarType().equals(other.getCsCarType()))
            && (this.getCsBatteryCapacity() == null ? other.getCsBatteryCapacity() == null : this.getCsBatteryCapacity().equals(other.getCsBatteryCapacity()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCsId() == null) ? 0 : getCsId().hashCode());
        result = prime * result + ((getCsVender() == null) ? 0 : getCsVender().hashCode());
        result = prime * result + ((getCsVin() == null) ? 0 : getCsVin().hashCode());
        result = prime * result + ((getCsTeNo() == null) ? 0 : getCsTeNo().hashCode());
        result = prime * result + ((getCsNumber() == null) ? 0 : getCsNumber().hashCode());
        result = prime * result + ((getCsTeType() == null) ? 0 : getCsTeType().hashCode());
        result = prime * result + ((getCsCarNo() == null) ? 0 : getCsCarNo().hashCode());
        result = prime * result + ((getCsCarType() == null) ? 0 : getCsCarType().hashCode());
        result = prime * result + ((getCsBatteryCapacity() == null) ? 0 : getCsBatteryCapacity().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", csId=").append(csId);
        sb.append(", csVender=").append(csVender);
        sb.append(", csVin=").append(csVin);
        sb.append(", csTeNo=").append(csTeNo);
        sb.append(", csNumber=").append(csNumber);
        sb.append(", csTeType=").append(csTeType);
        sb.append(", csCarNo=").append(csCarNo);
        sb.append(", csCarType=").append(csCarType);
        sb.append(", csBatteryCapacity=").append(csBatteryCapacity);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}