package com.ccclubs.quota.orm.model;

import java.io.Serializable;
import java.util.Date;

public class SrvHost implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_id
     *
     * @mbg.generated
     */
    private Integer shId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_name
     *
     * @mbg.generated
     */
    private String shName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_key
     *
     * @mbg.generated
     */
    private String shKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_topic
     *
     * @mbg.generated
     */
    private String shTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_add_time
     *
     * @mbg.generated
     */
    private Date shAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_upt_time
     *
     * @mbg.generated
     */
    private Date shUptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_status
     *
     * @mbg.generated
     */
    private Integer shStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_host.sh_appid
     *
     * @mbg.generated
     */
    private String shAppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table srv_host
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_id
     *
     * @return the value of srv_host.sh_id
     *
     * @mbg.generated
     */
    public Integer getShId() {
        return shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_id
     *
     * @param shId the value for srv_host.sh_id
     *
     * @mbg.generated
     */
    public void setShId(Integer shId) {
        this.shId = shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_name
     *
     * @return the value of srv_host.sh_name
     *
     * @mbg.generated
     */
    public String getShName() {
        return shName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_name
     *
     * @param shName the value for srv_host.sh_name
     *
     * @mbg.generated
     */
    public void setShName(String shName) {
        this.shName = shName == null ? null : shName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_key
     *
     * @return the value of srv_host.sh_key
     *
     * @mbg.generated
     */
    public String getShKey() {
        return shKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_key
     *
     * @param shKey the value for srv_host.sh_key
     *
     * @mbg.generated
     */
    public void setShKey(String shKey) {
        this.shKey = shKey == null ? null : shKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_topic
     *
     * @return the value of srv_host.sh_topic
     *
     * @mbg.generated
     */
    public String getShTopic() {
        return shTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_topic
     *
     * @param shTopic the value for srv_host.sh_topic
     *
     * @mbg.generated
     */
    public void setShTopic(String shTopic) {
        this.shTopic = shTopic == null ? null : shTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_add_time
     *
     * @return the value of srv_host.sh_add_time
     *
     * @mbg.generated
     */
    public Date getShAddTime() {
        return shAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_add_time
     *
     * @param shAddTime the value for srv_host.sh_add_time
     *
     * @mbg.generated
     */
    public void setShAddTime(Date shAddTime) {
        this.shAddTime = shAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_upt_time
     *
     * @return the value of srv_host.sh_upt_time
     *
     * @mbg.generated
     */
    public Date getShUptTime() {
        return shUptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_upt_time
     *
     * @param shUptTime the value for srv_host.sh_upt_time
     *
     * @mbg.generated
     */
    public void setShUptTime(Date shUptTime) {
        this.shUptTime = shUptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_status
     *
     * @return the value of srv_host.sh_status
     *
     * @mbg.generated
     */
    public Integer getShStatus() {
        return shStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_status
     *
     * @param shStatus the value for srv_host.sh_status
     *
     * @mbg.generated
     */
    public void setShStatus(Integer shStatus) {
        this.shStatus = shStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_host.sh_appid
     *
     * @return the value of srv_host.sh_appid
     *
     * @mbg.generated
     */
    public String getShAppid() {
        return shAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_host.sh_appid
     *
     * @param shAppid the value for srv_host.sh_appid
     *
     * @mbg.generated
     */
    public void setShAppid(String shAppid) {
        this.shAppid = shAppid == null ? null : shAppid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_host
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SrvHost other = (SrvHost) that;
        return (this.getShId() == null ? other.getShId() == null : this.getShId().equals(other.getShId()))
            && (this.getShName() == null ? other.getShName() == null : this.getShName().equals(other.getShName()))
            && (this.getShKey() == null ? other.getShKey() == null : this.getShKey().equals(other.getShKey()))
            && (this.getShTopic() == null ? other.getShTopic() == null : this.getShTopic().equals(other.getShTopic()))
            && (this.getShAddTime() == null ? other.getShAddTime() == null : this.getShAddTime().equals(other.getShAddTime()))
            && (this.getShUptTime() == null ? other.getShUptTime() == null : this.getShUptTime().equals(other.getShUptTime()))
            && (this.getShStatus() == null ? other.getShStatus() == null : this.getShStatus().equals(other.getShStatus()))
            && (this.getShAppid() == null ? other.getShAppid() == null : this.getShAppid().equals(other.getShAppid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_host
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShId() == null) ? 0 : getShId().hashCode());
        result = prime * result + ((getShName() == null) ? 0 : getShName().hashCode());
        result = prime * result + ((getShKey() == null) ? 0 : getShKey().hashCode());
        result = prime * result + ((getShTopic() == null) ? 0 : getShTopic().hashCode());
        result = prime * result + ((getShAddTime() == null) ? 0 : getShAddTime().hashCode());
        result = prime * result + ((getShUptTime() == null) ? 0 : getShUptTime().hashCode());
        result = prime * result + ((getShStatus() == null) ? 0 : getShStatus().hashCode());
        result = prime * result + ((getShAppid() == null) ? 0 : getShAppid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_host
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shId=").append(shId);
        sb.append(", shName=").append(shName);
        sb.append(", shKey=").append(shKey);
        sb.append(", shTopic=").append(shTopic);
        sb.append(", shAddTime=").append(shAddTime);
        sb.append(", shUptTime=").append(shUptTime);
        sb.append(", shStatus=").append(shStatus);
        sb.append(", shAppid=").append(shAppid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}