package com.ccclubs.quota.vo.monitor;

import java.io.Serializable;

public class CsStructAddInput implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -323996088281236979L;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_id
	 *
	 * @mbg.generated
	 */
	private Long cssId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_name
	 *
	 * @mbg.generated
	 */
	private String cssName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_type
	 *
	 * @mbg.generated
	 */
	private Integer cssType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_req_code
	 *
	 * @mbg.generated
	 */
	private String cssReqCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_rep_code
	 *
	 * @mbg.generated
	 */
	private String cssRepCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_status
	 *
	 * @mbg.generated
	 */
	private Integer cssStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_request
	 *
	 * @mbg.generated
	 */
	private String cssRequest;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_struct.css_response
	 *
	 * @mbg.generated
	 */
	private String cssResponse;

	public Long getCssId() {
		return cssId;
	}

	public void setCssId(Long cssId) {
		this.cssId = cssId;
	}

	public String getCssName() {
		return cssName;
	}

	public void setCssName(String cssName) {
		this.cssName = cssName;
	}

	public Integer getCssType() {
		return cssType;
	}

	public void setCssType(Integer cssType) {
		this.cssType = cssType;
	}

	public String getCssReqCode() {
		return cssReqCode;
	}

	public void setCssReqCode(String cssReqCode) {
		this.cssReqCode = cssReqCode;
	}

	public String getCssRepCode() {
		return cssRepCode;
	}

	public void setCssRepCode(String cssRepCode) {
		this.cssRepCode = cssRepCode;
	}

	public Integer getCssStatus() {
		return cssStatus;
	}

	public void setCssStatus(Integer cssStatus) {
		this.cssStatus = cssStatus;
	}

	public String getCssRequest() {
		return cssRequest;
	}

	public void setCssRequest(String cssRequest) {
		this.cssRequest = cssRequest;
	}

	public String getCssResponse() {
		return cssResponse;
	}

	public void setCssResponse(String cssResponse) {
		this.cssResponse = cssResponse;
	}

}
