package com.ccclubs.usr.orm.mapper;

import com.ccclubs.usr.orm.model.VcObjects;
import com.ccclubs.usr.orm.model.VcObjectsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VcObjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    long countByExample(VcObjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int deleteByExample(VcObjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int insert(VcObjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int insertSelective(VcObjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    List<VcObjects> selectByExample(VcObjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    VcObjects selectByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VcObjects record, @Param("example") VcObjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VcObjects record, @Param("example") VcObjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VcObjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VcObjects record);
}