package com.ccclubs.usr.orm.mapper;

import com.ccclubs.usr.orm.model.VcPermissionOperation;
import com.ccclubs.usr.orm.model.VcPermissionOperationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VcPermissionOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    long countByExample(VcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int deleteByExample(VcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String permissionOperationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int insert(VcPermissionOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int insertSelective(VcPermissionOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    List<VcPermissionOperation> selectByExample(VcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    VcPermissionOperation selectByPrimaryKey(String permissionOperationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VcPermissionOperation record, @Param("example") VcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VcPermissionOperation record, @Param("example") VcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VcPermissionOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_permission_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VcPermissionOperation record);
}