package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.CsMachine;
import com.ccclubs.pub.orm.model.CsMachineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CsMachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    long countByExample(CsMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int deleteByExample(CsMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer csmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int insert(CsMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int insertSelective(CsMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    List<CsMachine> selectByExample(CsMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    CsMachine selectByPrimaryKey(Integer csmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsMachine record, @Param("example") CsMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsMachine record, @Param("example") CsMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsMachine record);
}