package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.CsTempBattery;
import com.ccclubs.pub.orm.model.CsTempBatteryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CsTempBatteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    long countByExample(CsTempBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    int deleteByExample(CsTempBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    int insert(CsTempBattery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    int insertSelective(CsTempBattery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    List<CsTempBattery> selectByExample(CsTempBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsTempBattery record, @Param("example") CsTempBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_temp_battery
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsTempBattery record, @Param("example") CsTempBatteryExample example);
}