package com.ccclubs.pub.orm.mapper;

import com.ccclubs.pub.orm.model.SrvError;
import com.ccclubs.pub.orm.model.SrvErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrvErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    long countByExample(SrvErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int deleteByExample(SrvErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer seId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int insert(SrvError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int insertSelective(SrvError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    List<SrvError> selectByExample(SrvErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    SrvError selectByPrimaryKey(Integer seId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SrvError record, @Param("example") SrvErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SrvError record, @Param("example") SrvErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SrvError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_error
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SrvError record);
}