# springboot 配置
server:
  port: 12003

# netty配置
netty:
  tcp-port: 27700
  boss-count: 1
  worker-count: 10
  keep-alive: false
  backlog: 100

# 网关配置
gateway:
  server:
    log-print: true       # 打印消息日志
    buffer-check: false   # 开启缓存检查

#kafka生产者配置
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#kafka Topic
kafka:
  topic:
    gateway:
      error: topic_gb_error
      success: topic_gb_success
      conn: topic_conn_status
      oversee: topic_gb_oversee # 用于监听特定车辆的报文





