server:
  port: 8906

# netty配置
netty:
  tcp-port: 26700
  boss-count: 1
  worker-count: 2
  keep-alive: false
  backlog: 100
  use-linux-epoll: false

# 网关配置
gateway:
  server:
    log-print: true       # 打印消息日志
    buffer-check: true    # 开启缓存检查
    idle-seconds: 10      # 读空闲断开时间间隔(秒)

spring:
  # redis配置
  redis:
    host: 118.178.229.234
    port: 63791
    password: WDnlDnt6f7GuYh
    database: 7
  # kafka生产者配置
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#kafka Topic
kafka:
  topic:
    gateway:
      error: topic_gateway_error
      success: topic_808_success
      conn: topic_conn_status
      oversee: topic_808_oversee # 用于监听特定车辆的报文

#jt808网关转发到MQ的topic
mq:
  topic: ser

#阿里云 MQ 配置
ons:
  producerId: PID_terminal_ser
  accessKey: M6dHCyKyKYUCNbW4
  secretKey: k6gOSH3dNJjFYze4CuxbBWS1PWqvVk

mqttAliyun:
  #阿里云 mqtt broker 地址
  host: tcp://mqtt.cn-hangzhou.aliyuncs.com
  #阿里云 mqtt broker 端口
  port: 1883
  #阿里云 mqClient ID 前缀
  preId: GID_pro
  #阿里云用户名
  userName: M6dHCyKyKYUCNbW4
  #阿里云密码
  pwd: 2u0w1llRPSxKeNSZDq95jQAE95c=
  #订阅主题
  subTopic: protocol/jt808/#
  #是否记录上行记录
  logUpDown: false
