server:
  port: 11113

spring:
  redis:
    host: 127.0.0.1

  data:  
    mongodb:  
#      history:
#        host: 114.55.24.97
#        port: 3717
#        username: zkj_user
#        password: zkj2017
#        database: vc_history
#        authenticationDatabase: vc_history
#      remote:
#        host: 114.55.24.97
#        port: 3717
#        username: zkj_user
#        password: zkj2017
#        database: vc_remote
#        authenticationDatabase: vc_remote
      history:
        host: 127.0.0.1
        port: 27017
        database: MyTest
        authenticationDatabase: MyTest
      remote:
        host: 127.0.0.1
        port: 27017
        database: MyTest
        authenticationDatabase: MyTest
      
dubbo:
  scan: 
    annotationPackage: com.ccclubs
  application:
    name: srv
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    port: 20660
  protocol:
    name: dubbo
    threads: 100
    port: 20660
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://121.199.49.206:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: zkj_user
    password: kANXZYqf2UzghVY7DnjP
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters:
zt:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url:  jdbc:mysql://121.199.49.206:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: zkj_user
    password: kANXZYqf2UzghVY7DnjP
  threadInterval: 0 15 17 * * ?
  updateInterval: 7
  avgDriveTimePerDay: 0.2,1.5,  1.3,2.5,  2.3,3.5,  3.3,6,  5.3,12
  obdMileThreshold: 200000