server:
  port: 8081
spring:
  http: 
    encoding: 
      charset: UTF-8
      enable: true
      force: true

api:
  security:
      apiId: appKey
      appId: '{cipher}AIB6DsANDSW8Ehs0L8EcMJe7cjxfzwOP1+onlXhQryApv/JJod3syv1exOHUw/DEBaNdzkb1BqR01PdXs3+mKNxQUNtaY8xqztz3hiJx1S963Ke8pB5yOKwdJ0cDWO11k5Fi16QCCcB6Gxy3ASjLBPpK75iZwQx/paWhSkdCj7Tm7BjE+wnEEYtNTIB/YjXdnjQ1EpC63VDKUAWY6uhNJs0v'

dubbo:
  scan: 
    annotationPackage: com.ccclubs
  application:
    name: api
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    #port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  consumer:
    timeout: 120000
    check: false

