server:
  port: 19999

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://121.199.49.206:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: zkj_user
    password: kANXZYqf2UzghVY7DnjP
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  scan:
    basePackage: com.ccclubs.**.mapper

ccclubs:
  data:
    #批量任务配置
    batch:
      #批量更新单次最大值，最大间隔时间，线程池数量，队列最大长度
      updateBatchSize: 1000
      updateMaxDurTime: 3000
      updateThreads: 20
      updateQueueMax: 50000
      #批量写入mongodb单次最大值，最大间隔时间，线程池数量，队列最大长度
      mongoInsertBatchSize: 2000
      mongoInsertMaxDurTime: 10000
      mongoInsertThreads: 20
      mongoInsertQueueMax: 200000


dubbo:
  scan:
    annotationPackage: com.ccclubs.test,com.ccclubs.frm.spring
  application:
    name: api
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    #port: 20660
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20660
  consumer:
    timeout: 120000
    check: false
  monitor:
    protocol: registry
  provider:
      timeout: 120000
      retries: -1


spring:
  redis:
    host: 127.0.0.1
#    host: 118.178.229.234
#    port: 63791
#    database: 7
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  influxdb:
    url: http://120.27.192.237:8086
    username: admin
    password: ahdd34534e
    database: mydb
    retention-policy: autogen
    writeTimeout: 12000
    readTimeout:  12000
    connectTimeout: 500