server:
  port: 9009
hbaseSrv:
  host: 101.37.178.63
oss:
  accessKeyId: LTAIYzY8yT3GTuj1
  accessKeySecret: Gdj4x2l5rOzC2r586Ur75EpdtARLt7
  endpoint: https://oss-cn-hangzhou.aliyuncs.com

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 7
#    host: 118.178.229.234
#    password: WDnlDnt6f7GuYh
#    port: 63791
#    database: 7
  data:
    mongodb:
      history:
        host: 114.55.24.97
        port: 3717
        username: zkj_user
        password: zkj2017
        database: vc_history
        authenticationDatabase: vc_history
      remote:
        host: 114.55.24.97
        port: 3717
        username: zkj_user
        password: zkj2017
        database: vc_remote
        authenticationDatabase: vc_remote
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#kafka 车辆上线离线 topic
kafka:
  topic:
    gateway:
      conn: topic_conn_status

dubbo:
  scan:
    annotationPackage: com.ccclubs
  application:
    name: web-front
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    port: 20880
  protocol:
    name: dubbo
    threads: 100
    #host: 10.0.10.96
    port: 20880
  provider:
    timeout: 120000
    retries: -1
  consumer:
    timeout: 120000
    check: false

druid:
  driver: com.mysql.jdbc.Driver
  jdbc:
    url: jdbc:mysql://121.199.49.206:3306/ccclubs_data_center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: zkj_user
    password: kANXZYqf2UzghVY7DnjP
  initialSize: 2
  maxActive: 4
  maxIdle: 2
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  filters:

email:
  host: smtp.mxhichina.com
  port: 465
  smtp_username: vcloud@ccclubs.com
  smtp_password: vcloud!@#$%12345
  sender_name: 车机中心监控平台
  ecoding: UTF-8

filedisk:
  path: /opt/vc_folder/

