package com.ccclubs.quota.vo.basis;

import java.io.Serializable;

public class CsTerminalAddInput implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1573541792611206840L;
	private Long cstId;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_idd
	 *
	 * @mbg.generated
	 */
	private String cstIdd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_model
	 *
	 * @mbg.generated
	 */
	private String cstModel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_made
	 *
	 * @mbg.generated
	 */
	private String cstMade;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_province
	 *
	 * @mbg.generated
	 */
	private String cstProvince;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_city
	 *
	 * @mbg.generated
	 */
	private String cstCity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_color
	 *
	 * @mbg.generated
	 */
	private Integer cstColor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_number
	 *
	 * @mbg.generated
	 */
	private String cstNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_vin
	 *
	 * @mbg.generated
	 */
	private String cstVin;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_mobile
	 *
	 * @mbg.generated
	 */
	private String cstMobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cs_terminal.cst_status
	 *
	 * @mbg.generated
	 */
	private Integer cstStatus;
	

	public Long getCstId() {
		return cstId;
	}

	public void setCstId(Long cstId) {
		this.cstId = cstId;
	}

	public String getCstIdd() {
		return cstIdd;
	}

	public void setCstIdd(String cstIdd) {
		this.cstIdd = cstIdd;
	}

	public String getCstModel() {
		return cstModel;
	}

	public void setCstModel(String cstModel) {
		this.cstModel = cstModel;
	}

	public String getCstMade() {
		return cstMade;
	}

	public void setCstMade(String cstMade) {
		this.cstMade = cstMade;
	}

	public String getCstProvince() {
		return cstProvince;
	}

	public void setCstProvince(String cstProvince) {
		this.cstProvince = cstProvince;
	}

	public String getCstCity() {
		return cstCity;
	}

	public void setCstCity(String cstCity) {
		this.cstCity = cstCity;
	}

	public Integer getCstColor() {
		return cstColor;
	}

	public void setCstColor(Integer cstColor) {
		this.cstColor = cstColor;
	}

	public String getCstNumber() {
		return cstNumber;
	}

	public void setCstNumber(String cstNumber) {
		this.cstNumber = cstNumber;
	}

	public String getCstVin() {
		return cstVin;
	}

	public void setCstVin(String cstVin) {
		this.cstVin = cstVin;
	}

	public String getCstMobile() {
		return cstMobile;
	}

	public void setCstMobile(String cstMobile) {
		this.cstMobile = cstMobile;
	}

	public Integer getCstStatus() {
		return cstStatus;
	}

	public void setCstStatus(Integer cstStatus) {
		this.cstStatus = cstStatus;
	}

}
