package com.ccclubs.quota.vo.basis;

import java.io.Serializable;

public class TbUpgradeAddInput implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2008305491123108867L;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_id
	 *
	 * @mbg.generated
	 */
	private Integer tbuId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_machine
	 *
	 * @mbg.generated
	 */
	private Integer tbuMachine;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_number
	 *
	 * @mbg.generated
	 */
	private String tbuNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_sim_no
	 *
	 * @mbg.generated
	 */
	private String tbuSimNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_te_type
	 *
	 * @mbg.generated
	 */
	private Integer tbuTeType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_protocol
	 *
	 * @mbg.generated
	 */
	private Integer tbuProtocol;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_file
	 *
	 * @mbg.generated
	 */
	private String tbuFile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_remarks
	 *
	 * @mbg.generated
	 */
	private String tbuRemarks;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_editor
	 *
	 * @mbg.generated
	 */
	private Integer tbuEditor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_upgrade.tbu_status
	 *
	 * @mbg.generated
	 */
	private Integer tbuStatus;

	public Integer getTbuId() {
		return tbuId;
	}

	public void setTbuId(Integer tbuId) {
		this.tbuId = tbuId;
	}

	public Integer getTbuMachine() {
		return tbuMachine;
	}

	public void setTbuMachine(Integer tbuMachine) {
		this.tbuMachine = tbuMachine;
	}

	public String getTbuNumber() {
		return tbuNumber;
	}

	public void setTbuNumber(String tbuNumber) {
		this.tbuNumber = tbuNumber;
	}

	public String getTbuSimNo() {
		return tbuSimNo;
	}

	public void setTbuSimNo(String tbuSimNo) {
		this.tbuSimNo = tbuSimNo;
	}

	public Integer getTbuTeType() {
		return tbuTeType;
	}

	public void setTbuTeType(Integer tbuTeType) {
		this.tbuTeType = tbuTeType;
	}

	public Integer getTbuProtocol() {
		return tbuProtocol;
	}

	public void setTbuProtocol(Integer tbuProtocol) {
		this.tbuProtocol = tbuProtocol;
	}

	public String getTbuFile() {
		return tbuFile;
	}

	public void setTbuFile(String tbuFile) {
		this.tbuFile = tbuFile;
	}

	public String getTbuRemarks() {
		return tbuRemarks;
	}

	public void setTbuRemarks(String tbuRemarks) {
		this.tbuRemarks = tbuRemarks;
	}

	public Integer getTbuEditor() {
		return tbuEditor;
	}

	public void setTbuEditor(Integer tbuEditor) {
		this.tbuEditor = tbuEditor;
	}

	public Integer getTbuStatus() {
		return tbuStatus;
	}

	public void setTbuStatus(Integer tbuStatus) {
		this.tbuStatus = tbuStatus;
	}

}
