package com.ccclubs.quota.orm.mapper;

import com.ccclubs.quota.orm.model.CsCanBiz;
import com.ccclubs.quota.orm.model.CsCanBizExample;
import java.util.List;

public interface CsCanBizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_can_biz
     *
     * @mbg.generated
     */
    long countByExample(CsCanBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_can_biz
     *
     * @mbg.generated
     */
    List<CsCanBiz> selectByExample(CsCanBizExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_can_biz
     *
     * @mbg.generated
     */
    CsCanBiz selectByPrimaryKey(Long cscId);
}