package com.ccclubs.quota.orm.mapper;

import com.ccclubs.quota.orm.model.CsIndexOutrangeList;
import com.ccclubs.quota.orm.model.CsIndexOutrangeListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CsIndexOutrangeListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    long countByExample(CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int deleteByExample(CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int insert(CsIndexOutrangeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int insertSelective(CsIndexOutrangeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    List<CsIndexOutrangeList> selectByExampleWithBLOBs(CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    List<CsIndexOutrangeList> selectByExample(CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    CsIndexOutrangeList selectByPrimaryKey(Long indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsIndexOutrangeList record,
        @Param("example") CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CsIndexOutrangeList record,
        @Param("example") CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsIndexOutrangeList record,
        @Param("example") CsIndexOutrangeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsIndexOutrangeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_index_outrange_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CsIndexOutrangeList record);
}