package com.ccclubs.quota.orm.mapper;

import com.ccclubs.quota.orm.model.CsVehicle;
import com.ccclubs.quota.orm.model.CsVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CsVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    long countByExample(CsVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int deleteByExample(CsVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer csvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int insert(CsVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int insertSelective(CsVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    List<CsVehicle> selectByExample(CsVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    CsVehicle selectByPrimaryKey(Integer csvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsVehicle record,
        @Param("example") CsVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsVehicle record,
        @Param("example") CsVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsVehicle record);
}