package com.ccclubs.quota.orm.mapper;

import com.ccclubs.quota.orm.model.CsVehicleMachineRel;
import com.ccclubs.quota.orm.model.CsVehicleMachineRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CsVehicleMachineRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    long countByExample(CsVehicleMachineRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int deleteByExample(CsVehicleMachineRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long csId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int insert(CsVehicleMachineRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int insertSelective(CsVehicleMachineRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    List<CsVehicleMachineRel> selectByExample(CsVehicleMachineRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    CsVehicleMachineRel selectByPrimaryKey(Long csId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsVehicleMachineRel record,
        @Param("example") CsVehicleMachineRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsVehicleMachineRel record,
        @Param("example") CsVehicleMachineRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsVehicleMachineRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_vehicle_machine_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsVehicleMachineRel record);
}