package com.ccclubs.quota.orm.mapper;

import com.ccclubs.quota.orm.model.SocMilesBizQuota;
import com.ccclubs.quota.orm.model.SocMilesBizQuotaExample;
import java.util.List;

public interface SocMilesBizQuotaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soc_miles_biz_quota
     *
     * @mbg.generated
     */
    int insert(SocMilesBizQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soc_miles_biz_quota
     *
     * @mbg.generated
     */
    int insertSelective(SocMilesBizQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soc_miles_biz_quota
     *
     * @mbg.generated
     */
    List<SocMilesBizQuota> selectByExample(SocMilesBizQuotaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soc_miles_biz_quota
     *
     * @mbg.generated
     */
    SocMilesBizQuota selectByPrimaryKey(String csVin);
}