package com.ccclubs.quota.orm.mapper;

import com.ccclubs.quota.orm.model.VcDistrict;
import com.ccclubs.quota.orm.model.VcDistrictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VcDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    long countByExample(VcDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int deleteByExample(VcDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int insert(VcDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int insertSelective(VcDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    List<VcDistrict> selectByExample(VcDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    VcDistrict selectByPrimaryKey(String districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VcDistrict record,
        @Param("example") VcDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VcDistrict record,
        @Param("example") VcDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VcDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_district
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VcDistrict record);
}