package com.ccclubs.admin.orm.mapper;

import com.ccclubs.frm.base.BaseDAO;
import com.ccclubs.admin.model.CsVehicleExp;

import java.util.List;

/**
 * 异常车辆数据的Mapper实现
 *
 * @author
 * @create 2018-03-21
 * @category generated by vc-coder
 **/
public interface CsVehicleExpMapper extends BaseDAO<CsVehicleExp, Long> {

    void insertListSelective(List<CsVehicleExp> list);
}
