package com.ccclubs.admin.controller.base;

import com.ccclubs.admin.entity.CsMappingCrieria;
import com.ccclubs.admin.model.CsMapping;
import com.ccclubs.admin.query.CsMappingQuery;
import com.ccclubs.admin.service.ICsMappingService;
import com.ccclubs.admin.vo.TableResult;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 车管关系Controller
 *
 * @author
 * @category generated by NovaV1.0
 * @since V1.0
 */
@RestController
@RequestMapping("/admin/mapping")
public class CsMappingController {

    @Autowired
    ICsMappingService csMappingService;

    /**
     * 获取分页列表数据
     *
     * @param query
     * @param page
     * @param rows
     * @return
     */
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    public TableResult<CsMapping> list(CsMappingQuery query, @RequestParam(defaultValue = "0") Integer page,
                                       @RequestParam(defaultValue = "10") Integer rows) {
        PageInfo<CsMapping> pageInfo = csMappingService.getPage(query.getCrieria(), page, rows);
        List<CsMapping> list = pageInfo.getList();
        for (CsMapping data : list) {
            registResolvers(data);
        }

        TableResult<CsMapping> r = new TableResult<>(pageInfo);
        return r;
    }

    /**
     * 创建保存车管关系
     *
     * @return
     */
    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public VoResult<?> add(CsMapping data) {
        csMappingService.insert(data);
        return VoResult.success();
    }

    /**
     * 更新车管关系
     *
     * @param data
     * @return
     */
    @RequestMapping(value = "/update", method = RequestMethod.POST)
    public VoResult<?> update(CsMapping data) {
        csMappingService.updateByPrimaryKeySelective(data);
        return VoResult.success();
    }

    /**
     * 删除车管关系
     *
     * @return
     */
    @RequestMapping(value = "delete", method = RequestMethod.DELETE)
    public VoResult<?> delete(@RequestParam(required = true) final Integer[] ids) {
        csMappingService.batchDelete(ids);
        return VoResult.success();
    }

    /**
     * 注册属性内容解析器
     */
    void registResolvers(CsMapping data) {
        if (data != null) {
        }
    }

    /**
     * 获取单条车管关系信息
     */
    @RequestMapping(value = "/detail/{id}", method = RequestMethod.GET)
    public VoResult<Map<String, CsMapping>> detail(@PathVariable(required = true) Long id) {
        CsMapping data = csMappingService.selectByPrimaryKey(id.intValue());
        Map<String, CsMapping> map = new HashMap<String, CsMapping>();
        registResolvers(data);
        map.put("tbody", data);
        return VoResult.success().setValue(map);
    }


    /**
     * 根据文本检索车管关系信息
     */
    @RequestMapping(value = "/query", method = RequestMethod.GET)
    public VoResult<Map<String, List<Map<String, Object>>>> query(String text, String where, CsMapping queryRecord) {
        CsMappingCrieria query = new CsMappingCrieria();
        CsMappingCrieria.Criteria c = query.createCriteria();
        if (!StringUtils.isEmpty(text)) {
            Integer val = Integer.valueOf(text);
            c.andcsmIdEqualTo(val);
        }
        if (!StringUtils.isEmpty(where)) {
            Integer val = Integer.valueOf(where);
            c.andcsmIdEqualTo(val);
        }
        PageInfo<CsMapping> pageInfo = csMappingService.getPage(query, 0, 10);
        List<CsMapping> list = pageInfo.getList();

        List<Map<String, Object>> mapList = new ArrayList<Map<String, Object>>(list.size());
        Map<String, Object> map;
        for (CsMapping data : list) {
            map = new HashMap<String, Object>();
            map.put("value", data.getCsmId());
            map.put("text", data.getCsmId());
            mapList.add(map);
        }
        return VoResult.success().setValue(mapList);
    }

}
