package com.ccclubs.admin.controller.base;

import com.ccclubs.admin.entity.CsTerminalCrieria;
import com.ccclubs.admin.model.CsTerminal;
import com.ccclubs.admin.query.CsTerminalQuery;
import com.ccclubs.admin.service.ICsTerminalService;
import com.ccclubs.admin.vo.TableResult;
import com.ccclubs.admin.vo.VoResult;
import com.github.pagehelper.PageInfo;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * TBox注册信息Controller
 *
 * @author
 * @category generated by NovaV1.0
 * @since V1.0
 */
@RestController
@RequestMapping("/monitor/register")
public class CsTerminalController {

    @Autowired
    ICsTerminalService csTerminalService;

    /**
     * 获取分页列表数据
     *
     * @param query
     * @param page
     * @param rows
     * @return
     */
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    public TableResult<CsTerminal> list(CsTerminalQuery query, @RequestParam(defaultValue = "0") Integer page,
                                        @RequestParam(defaultValue = "10") Integer rows) {
        PageInfo<CsTerminal> pageInfo = csTerminalService.getPage(query.getCrieria(), page, rows);
        List<CsTerminal> list = pageInfo.getList();
        for (CsTerminal data : list) {
            registResolvers(data);
        }

        TableResult<CsTerminal> r = new TableResult<>(pageInfo);
        return r;
    }


    /**
     * 注册属性内容解析器
     */
    void registResolvers(CsTerminal data) {
        if (data != null) {
            data.registResolver(com.ccclubs.admin.resolver.CsTerminalResolver.状态.getResolver());
        }
    }

    /**
     * 获取单条TBox注册信息信息
     */
    @RequestMapping(value = "/detail/{id}", method = RequestMethod.GET)
    public VoResult<Map<String, CsTerminal>> detail(@PathVariable(required = true) Long id) {
        CsTerminal data = csTerminalService.selectByPrimaryKey(id);
        Map<String, CsTerminal> map = new HashMap<String, CsTerminal>();
        registResolvers(data);
        map.put("tbody", data);
        return VoResult.success().setValue(map);
    }


    /**
     * 根据文本检索TBox注册信息信息
     */
    @RequestMapping(value = "/query", method = RequestMethod.GET)
    public VoResult<Map<String, List<Map<String, Object>>>> query(String text, String where, CsTerminal queryRecord) {
        CsTerminalCrieria query = new CsTerminalCrieria();
        CsTerminalCrieria.Criteria c = query.createCriteria();
        if (!StringUtils.isEmpty(text)) {
            String val = String.valueOf(text);
            c.andcstIddLike(val);
        }
        if (!StringUtils.isEmpty(where)) {
            Long val = Long.valueOf(where);
            c.andcstIdEqualTo(val);
        }
        PageInfo<CsTerminal> pageInfo = csTerminalService.getPage(query, 0, 10);
        List<CsTerminal> list = pageInfo.getList();

        List<Map<String, Object>> mapList = new ArrayList<Map<String, Object>>(list.size());
        Map<String, Object> map;
        for (CsTerminal data : list) {
            map = new HashMap<String, Object>();
            map.put("value", data.getCstId());
            map.put("text", data.getCstIdd());
            mapList.add(map);
        }
        return VoResult.success().setValue(mapList);
    }

}
