package com.ccclubs.usr.orm.model;

import java.util.ArrayList;
import java.util.List;

public class VcObjectsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public VcObjectsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andObjectIdIsNull() {
            addCriterion("object_id is null");
            return (Criteria) this;
        }

        public Criteria andObjectIdIsNotNull() {
            addCriterion("object_id is not null");
            return (Criteria) this;
        }

        public Criteria andObjectIdEqualTo(String value) {
            addCriterion("object_id =", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotEqualTo(String value) {
            addCriterion("object_id <>", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdGreaterThan(String value) {
            addCriterion("object_id >", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("object_id >=", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLessThan(String value) {
            addCriterion("object_id <", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLessThanOrEqualTo(String value) {
            addCriterion("object_id <=", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdLike(String value) {
            addCriterion("object_id like", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotLike(String value) {
            addCriterion("object_id not like", value, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdIn(List<String> values) {
            addCriterion("object_id in", values, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotIn(List<String> values) {
            addCriterion("object_id not in", values, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdBetween(String value1, String value2) {
            addCriterion("object_id between", value1, value2, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectIdNotBetween(String value1, String value2) {
            addCriterion("object_id not between", value1, value2, "objectId");
            return (Criteria) this;
        }

        public Criteria andObjectNameIsNull() {
            addCriterion("object_name is null");
            return (Criteria) this;
        }

        public Criteria andObjectNameIsNotNull() {
            addCriterion("object_name is not null");
            return (Criteria) this;
        }

        public Criteria andObjectNameEqualTo(String value) {
            addCriterion("object_name =", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotEqualTo(String value) {
            addCriterion("object_name <>", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameGreaterThan(String value) {
            addCriterion("object_name >", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("object_name >=", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameLessThan(String value) {
            addCriterion("object_name <", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameLessThanOrEqualTo(String value) {
            addCriterion("object_name <=", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameLike(String value) {
            addCriterion("object_name like", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotLike(String value) {
            addCriterion("object_name not like", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameIn(List<String> values) {
            addCriterion("object_name in", values, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotIn(List<String> values) {
            addCriterion("object_name not in", values, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameBetween(String value1, String value2) {
            addCriterion("object_name between", value1, value2, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotBetween(String value1, String value2) {
            addCriterion("object_name not between", value1, value2, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdIsNull() {
            addCriterion("object_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdIsNotNull() {
            addCriterion("object_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdEqualTo(String value) {
            addCriterion("object_parent_id =", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdNotEqualTo(String value) {
            addCriterion("object_parent_id <>", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdGreaterThan(String value) {
            addCriterion("object_parent_id >", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("object_parent_id >=", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdLessThan(String value) {
            addCriterion("object_parent_id <", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdLessThanOrEqualTo(String value) {
            addCriterion("object_parent_id <=", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdLike(String value) {
            addCriterion("object_parent_id like", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdNotLike(String value) {
            addCriterion("object_parent_id not like", value, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdIn(List<String> values) {
            addCriterion("object_parent_id in", values, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdNotIn(List<String> values) {
            addCriterion("object_parent_id not in", values, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdBetween(String value1, String value2) {
            addCriterion("object_parent_id between", value1, value2, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectParentIdNotBetween(String value1, String value2) {
            addCriterion("object_parent_id not between", value1, value2, "objectParentId");
            return (Criteria) this;
        }

        public Criteria andObjectPathIsNull() {
            addCriterion("object_path is null");
            return (Criteria) this;
        }

        public Criteria andObjectPathIsNotNull() {
            addCriterion("object_path is not null");
            return (Criteria) this;
        }

        public Criteria andObjectPathEqualTo(String value) {
            addCriterion("object_path =", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathNotEqualTo(String value) {
            addCriterion("object_path <>", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathGreaterThan(String value) {
            addCriterion("object_path >", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathGreaterThanOrEqualTo(String value) {
            addCriterion("object_path >=", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathLessThan(String value) {
            addCriterion("object_path <", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathLessThanOrEqualTo(String value) {
            addCriterion("object_path <=", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathLike(String value) {
            addCriterion("object_path like", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathNotLike(String value) {
            addCriterion("object_path not like", value, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathIn(List<String> values) {
            addCriterion("object_path in", values, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathNotIn(List<String> values) {
            addCriterion("object_path not in", values, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathBetween(String value1, String value2) {
            addCriterion("object_path between", value1, value2, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectPathNotBetween(String value1, String value2) {
            addCriterion("object_path not between", value1, value2, "objectPath");
            return (Criteria) this;
        }

        public Criteria andObjectCssIsNull() {
            addCriterion("object_css is null");
            return (Criteria) this;
        }

        public Criteria andObjectCssIsNotNull() {
            addCriterion("object_css is not null");
            return (Criteria) this;
        }

        public Criteria andObjectCssEqualTo(String value) {
            addCriterion("object_css =", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssNotEqualTo(String value) {
            addCriterion("object_css <>", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssGreaterThan(String value) {
            addCriterion("object_css >", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssGreaterThanOrEqualTo(String value) {
            addCriterion("object_css >=", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssLessThan(String value) {
            addCriterion("object_css <", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssLessThanOrEqualTo(String value) {
            addCriterion("object_css <=", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssLike(String value) {
            addCriterion("object_css like", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssNotLike(String value) {
            addCriterion("object_css not like", value, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssIn(List<String> values) {
            addCriterion("object_css in", values, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssNotIn(List<String> values) {
            addCriterion("object_css not in", values, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssBetween(String value1, String value2) {
            addCriterion("object_css between", value1, value2, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectCssNotBetween(String value1, String value2) {
            addCriterion("object_css not between", value1, value2, "objectCss");
            return (Criteria) this;
        }

        public Criteria andObjectOrderIsNull() {
            addCriterion("object_order is null");
            return (Criteria) this;
        }

        public Criteria andObjectOrderIsNotNull() {
            addCriterion("object_order is not null");
            return (Criteria) this;
        }

        public Criteria andObjectOrderEqualTo(Integer value) {
            addCriterion("object_order =", value, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderNotEqualTo(Integer value) {
            addCriterion("object_order <>", value, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderGreaterThan(Integer value) {
            addCriterion("object_order >", value, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("object_order >=", value, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderLessThan(Integer value) {
            addCriterion("object_order <", value, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderLessThanOrEqualTo(Integer value) {
            addCriterion("object_order <=", value, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderIn(List<Integer> values) {
            addCriterion("object_order in", values, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderNotIn(List<Integer> values) {
            addCriterion("object_order not in", values, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderBetween(Integer value1, Integer value2) {
            addCriterion("object_order between", value1, value2, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("object_order not between", value1, value2, "objectOrder");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIsNull() {
            addCriterion("object_type is null");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIsNotNull() {
            addCriterion("object_type is not null");
            return (Criteria) this;
        }

        public Criteria andObjectTypeEqualTo(Integer value) {
            addCriterion("object_type =", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotEqualTo(Integer value) {
            addCriterion("object_type <>", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeGreaterThan(Integer value) {
            addCriterion("object_type >", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("object_type >=", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLessThan(Integer value) {
            addCriterion("object_type <", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeLessThanOrEqualTo(Integer value) {
            addCriterion("object_type <=", value, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeIn(List<Integer> values) {
            addCriterion("object_type in", values, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotIn(List<Integer> values) {
            addCriterion("object_type not in", values, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeBetween(Integer value1, Integer value2) {
            addCriterion("object_type between", value1, value2, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("object_type not between", value1, value2, "objectType");
            return (Criteria) this;
        }

        public Criteria andObjectStatusIsNull() {
            addCriterion("object_status is null");
            return (Criteria) this;
        }

        public Criteria andObjectStatusIsNotNull() {
            addCriterion("object_status is not null");
            return (Criteria) this;
        }

        public Criteria andObjectStatusEqualTo(Integer value) {
            addCriterion("object_status =", value, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusNotEqualTo(Integer value) {
            addCriterion("object_status <>", value, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusGreaterThan(Integer value) {
            addCriterion("object_status >", value, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("object_status >=", value, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusLessThan(Integer value) {
            addCriterion("object_status <", value, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusLessThanOrEqualTo(Integer value) {
            addCriterion("object_status <=", value, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusIn(List<Integer> values) {
            addCriterion("object_status in", values, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusNotIn(List<Integer> values) {
            addCriterion("object_status not in", values, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusBetween(Integer value1, Integer value2) {
            addCriterion("object_status between", value1, value2, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("object_status not between", value1, value2, "objectStatus");
            return (Criteria) this;
        }

        public Criteria andObjectMemoIsNull() {
            addCriterion("object_memo is null");
            return (Criteria) this;
        }

        public Criteria andObjectMemoIsNotNull() {
            addCriterion("object_memo is not null");
            return (Criteria) this;
        }

        public Criteria andObjectMemoEqualTo(String value) {
            addCriterion("object_memo =", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoNotEqualTo(String value) {
            addCriterion("object_memo <>", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoGreaterThan(String value) {
            addCriterion("object_memo >", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoGreaterThanOrEqualTo(String value) {
            addCriterion("object_memo >=", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoLessThan(String value) {
            addCriterion("object_memo <", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoLessThanOrEqualTo(String value) {
            addCriterion("object_memo <=", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoLike(String value) {
            addCriterion("object_memo like", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoNotLike(String value) {
            addCriterion("object_memo not like", value, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoIn(List<String> values) {
            addCriterion("object_memo in", values, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoNotIn(List<String> values) {
            addCriterion("object_memo not in", values, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoBetween(String value1, String value2) {
            addCriterion("object_memo between", value1, value2, "objectMemo");
            return (Criteria) this;
        }

        public Criteria andObjectMemoNotBetween(String value1, String value2) {
            addCriterion("object_memo not between", value1, value2, "objectMemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vc_objects
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vc_objects
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}