package com.ccclubs.pub.orm.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cs_his_machine_relation
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CsHisMachineRelation implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_his_machine_relation.csh_id
     *
     * @mbg.generated
     */
    private Integer cshId;

    /**
     * Database Column Remarks:
     *   车机对应MongoDB历史表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_his_machine_relation.csh_tb_name
     *
     * @mbg.generated
     */
    private String cshTbName;

    /**
     * Database Column Remarks:
     *   车机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_his_machine_relation.csh_number
     *
     * @mbg.generated
     */
    private String cshNumber;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_his_machine_relation.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_his_machine_relation.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_his_machine_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_his_machine_relation.csh_id
     *
     * @return the value of cs_his_machine_relation.csh_id
     *
     * @mbg.generated
     */
    public Integer getCshId() {
        return cshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_his_machine_relation.csh_id
     *
     * @param cshId the value for cs_his_machine_relation.csh_id
     *
     * @mbg.generated
     */
    public void setCshId(Integer cshId) {
        this.cshId = cshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_his_machine_relation.csh_tb_name
     *
     * @return the value of cs_his_machine_relation.csh_tb_name
     *
     * @mbg.generated
     */
    public String getCshTbName() {
        return cshTbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_his_machine_relation.csh_tb_name
     *
     * @param cshTbName the value for cs_his_machine_relation.csh_tb_name
     *
     * @mbg.generated
     */
    public void setCshTbName(String cshTbName) {
        this.cshTbName = cshTbName == null ? null : cshTbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_his_machine_relation.csh_number
     *
     * @return the value of cs_his_machine_relation.csh_number
     *
     * @mbg.generated
     */
    public String getCshNumber() {
        return cshNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_his_machine_relation.csh_number
     *
     * @param cshNumber the value for cs_his_machine_relation.csh_number
     *
     * @mbg.generated
     */
    public void setCshNumber(String cshNumber) {
        this.cshNumber = cshNumber == null ? null : cshNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_his_machine_relation.createTime
     *
     * @return the value of cs_his_machine_relation.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_his_machine_relation.createTime
     *
     * @param createtime the value for cs_his_machine_relation.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_his_machine_relation.updateTime
     *
     * @return the value of cs_his_machine_relation.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_his_machine_relation.updateTime
     *
     * @param updatetime the value for cs_his_machine_relation.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_his_machine_relation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CsHisMachineRelation other = (CsHisMachineRelation) that;
        return (this.getCshId() == null ? other.getCshId() == null : this.getCshId().equals(other.getCshId()))
            && (this.getCshTbName() == null ? other.getCshTbName() == null : this.getCshTbName().equals(other.getCshTbName()))
            && (this.getCshNumber() == null ? other.getCshNumber() == null : this.getCshNumber().equals(other.getCshNumber()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_his_machine_relation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCshId() == null) ? 0 : getCshId().hashCode());
        result = prime * result + ((getCshTbName() == null) ? 0 : getCshTbName().hashCode());
        result = prime * result + ((getCshNumber() == null) ? 0 : getCshNumber().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_his_machine_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cshId=").append(cshId);
        sb.append(", cshTbName=").append(cshTbName);
        sb.append(", cshNumber=").append(cshNumber);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}