package com.ccclubs.pub.orm.model;

import java.util.ArrayList;
import java.util.List;

public class CsMappingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public CsMappingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCsmIdIsNull() {
            addCriterion("csm_id is null");
            return (Criteria) this;
        }

        public Criteria andCsmIdIsNotNull() {
            addCriterion("csm_id is not null");
            return (Criteria) this;
        }

        public Criteria andCsmIdEqualTo(Integer value) {
            addCriterion("csm_id =", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdNotEqualTo(Integer value) {
            addCriterion("csm_id <>", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdGreaterThan(Integer value) {
            addCriterion("csm_id >", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("csm_id >=", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdLessThan(Integer value) {
            addCriterion("csm_id <", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdLessThanOrEqualTo(Integer value) {
            addCriterion("csm_id <=", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdIn(List<Integer> values) {
            addCriterion("csm_id in", values, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdNotIn(List<Integer> values) {
            addCriterion("csm_id not in", values, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdBetween(Integer value1, Integer value2) {
            addCriterion("csm_id between", value1, value2, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("csm_id not between", value1, value2, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmCarIsNull() {
            addCriterion("csm_car is null");
            return (Criteria) this;
        }

        public Criteria andCsmCarIsNotNull() {
            addCriterion("csm_car is not null");
            return (Criteria) this;
        }

        public Criteria andCsmCarEqualTo(Integer value) {
            addCriterion("csm_car =", value, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarNotEqualTo(Integer value) {
            addCriterion("csm_car <>", value, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarGreaterThan(Integer value) {
            addCriterion("csm_car >", value, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarGreaterThanOrEqualTo(Integer value) {
            addCriterion("csm_car >=", value, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarLessThan(Integer value) {
            addCriterion("csm_car <", value, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarLessThanOrEqualTo(Integer value) {
            addCriterion("csm_car <=", value, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarIn(List<Integer> values) {
            addCriterion("csm_car in", values, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarNotIn(List<Integer> values) {
            addCriterion("csm_car not in", values, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarBetween(Integer value1, Integer value2) {
            addCriterion("csm_car between", value1, value2, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmCarNotBetween(Integer value1, Integer value2) {
            addCriterion("csm_car not between", value1, value2, "csmCar");
            return (Criteria) this;
        }

        public Criteria andCsmManageIsNull() {
            addCriterion("csm_manage is null");
            return (Criteria) this;
        }

        public Criteria andCsmManageIsNotNull() {
            addCriterion("csm_manage is not null");
            return (Criteria) this;
        }

        public Criteria andCsmManageEqualTo(Integer value) {
            addCriterion("csm_manage =", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageNotEqualTo(Integer value) {
            addCriterion("csm_manage <>", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageGreaterThan(Integer value) {
            addCriterion("csm_manage >", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageGreaterThanOrEqualTo(Integer value) {
            addCriterion("csm_manage >=", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageLessThan(Integer value) {
            addCriterion("csm_manage <", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageLessThanOrEqualTo(Integer value) {
            addCriterion("csm_manage <=", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageIn(List<Integer> values) {
            addCriterion("csm_manage in", values, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageNotIn(List<Integer> values) {
            addCriterion("csm_manage not in", values, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageBetween(Integer value1, Integer value2) {
            addCriterion("csm_manage between", value1, value2, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageNotBetween(Integer value1, Integer value2) {
            addCriterion("csm_manage not between", value1, value2, "csmManage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_mapping
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_mapping
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}