package com.ccclubs.pub.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CsManageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public CsManageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCsmIdIsNull() {
            addCriterion("csm_id is null");
            return (Criteria) this;
        }

        public Criteria andCsmIdIsNotNull() {
            addCriterion("csm_id is not null");
            return (Criteria) this;
        }

        public Criteria andCsmIdEqualTo(Integer value) {
            addCriterion("csm_id =", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdNotEqualTo(Integer value) {
            addCriterion("csm_id <>", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdGreaterThan(Integer value) {
            addCriterion("csm_id >", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("csm_id >=", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdLessThan(Integer value) {
            addCriterion("csm_id <", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdLessThanOrEqualTo(Integer value) {
            addCriterion("csm_id <=", value, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdIn(List<Integer> values) {
            addCriterion("csm_id in", values, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdNotIn(List<Integer> values) {
            addCriterion("csm_id not in", values, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdBetween(Integer value1, Integer value2) {
            addCriterion("csm_id between", value1, value2, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("csm_id not between", value1, value2, "csmId");
            return (Criteria) this;
        }

        public Criteria andCsmHostIsNull() {
            addCriterion("csm_host is null");
            return (Criteria) this;
        }

        public Criteria andCsmHostIsNotNull() {
            addCriterion("csm_host is not null");
            return (Criteria) this;
        }

        public Criteria andCsmHostEqualTo(Integer value) {
            addCriterion("csm_host =", value, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostNotEqualTo(Integer value) {
            addCriterion("csm_host <>", value, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostGreaterThan(Integer value) {
            addCriterion("csm_host >", value, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostGreaterThanOrEqualTo(Integer value) {
            addCriterion("csm_host >=", value, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostLessThan(Integer value) {
            addCriterion("csm_host <", value, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostLessThanOrEqualTo(Integer value) {
            addCriterion("csm_host <=", value, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostIn(List<Integer> values) {
            addCriterion("csm_host in", values, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostNotIn(List<Integer> values) {
            addCriterion("csm_host not in", values, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostBetween(Integer value1, Integer value2) {
            addCriterion("csm_host between", value1, value2, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmHostNotBetween(Integer value1, Integer value2) {
            addCriterion("csm_host not between", value1, value2, "csmHost");
            return (Criteria) this;
        }

        public Criteria andCsmManageIsNull() {
            addCriterion("csm_manage is null");
            return (Criteria) this;
        }

        public Criteria andCsmManageIsNotNull() {
            addCriterion("csm_manage is not null");
            return (Criteria) this;
        }

        public Criteria andCsmManageEqualTo(Long value) {
            addCriterion("csm_manage =", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageNotEqualTo(Long value) {
            addCriterion("csm_manage <>", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageGreaterThan(Long value) {
            addCriterion("csm_manage >", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageGreaterThanOrEqualTo(Long value) {
            addCriterion("csm_manage >=", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageLessThan(Long value) {
            addCriterion("csm_manage <", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageLessThanOrEqualTo(Long value) {
            addCriterion("csm_manage <=", value, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageIn(List<Long> values) {
            addCriterion("csm_manage in", values, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageNotIn(List<Long> values) {
            addCriterion("csm_manage not in", values, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageBetween(Long value1, Long value2) {
            addCriterion("csm_manage between", value1, value2, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmManageNotBetween(Long value1, Long value2) {
            addCriterion("csm_manage not between", value1, value2, "csmManage");
            return (Criteria) this;
        }

        public Criteria andCsmNameIsNull() {
            addCriterion("csm_name is null");
            return (Criteria) this;
        }

        public Criteria andCsmNameIsNotNull() {
            addCriterion("csm_name is not null");
            return (Criteria) this;
        }

        public Criteria andCsmNameEqualTo(String value) {
            addCriterion("csm_name =", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameNotEqualTo(String value) {
            addCriterion("csm_name <>", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameGreaterThan(String value) {
            addCriterion("csm_name >", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameGreaterThanOrEqualTo(String value) {
            addCriterion("csm_name >=", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameLessThan(String value) {
            addCriterion("csm_name <", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameLessThanOrEqualTo(String value) {
            addCriterion("csm_name <=", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameLike(String value) {
            addCriterion("csm_name like", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameNotLike(String value) {
            addCriterion("csm_name not like", value, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameIn(List<String> values) {
            addCriterion("csm_name in", values, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameNotIn(List<String> values) {
            addCriterion("csm_name not in", values, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameBetween(String value1, String value2) {
            addCriterion("csm_name between", value1, value2, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmNameNotBetween(String value1, String value2) {
            addCriterion("csm_name not between", value1, value2, "csmName");
            return (Criteria) this;
        }

        public Criteria andCsmMobileIsNull() {
            addCriterion("csm_mobile is null");
            return (Criteria) this;
        }

        public Criteria andCsmMobileIsNotNull() {
            addCriterion("csm_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andCsmMobileEqualTo(String value) {
            addCriterion("csm_mobile =", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileNotEqualTo(String value) {
            addCriterion("csm_mobile <>", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileGreaterThan(String value) {
            addCriterion("csm_mobile >", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileGreaterThanOrEqualTo(String value) {
            addCriterion("csm_mobile >=", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileLessThan(String value) {
            addCriterion("csm_mobile <", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileLessThanOrEqualTo(String value) {
            addCriterion("csm_mobile <=", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileLike(String value) {
            addCriterion("csm_mobile like", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileNotLike(String value) {
            addCriterion("csm_mobile not like", value, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileIn(List<String> values) {
            addCriterion("csm_mobile in", values, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileNotIn(List<String> values) {
            addCriterion("csm_mobile not in", values, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileBetween(String value1, String value2) {
            addCriterion("csm_mobile between", value1, value2, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmMobileNotBetween(String value1, String value2) {
            addCriterion("csm_mobile not between", value1, value2, "csmMobile");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyIsNull() {
            addCriterion("csm_family is null");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyIsNotNull() {
            addCriterion("csm_family is not null");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyEqualTo(String value) {
            addCriterion("csm_family =", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyNotEqualTo(String value) {
            addCriterion("csm_family <>", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyGreaterThan(String value) {
            addCriterion("csm_family >", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyGreaterThanOrEqualTo(String value) {
            addCriterion("csm_family >=", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyLessThan(String value) {
            addCriterion("csm_family <", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyLessThanOrEqualTo(String value) {
            addCriterion("csm_family <=", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyLike(String value) {
            addCriterion("csm_family like", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyNotLike(String value) {
            addCriterion("csm_family not like", value, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyIn(List<String> values) {
            addCriterion("csm_family in", values, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyNotIn(List<String> values) {
            addCriterion("csm_family not in", values, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyBetween(String value1, String value2) {
            addCriterion("csm_family between", value1, value2, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmFamilyNotBetween(String value1, String value2) {
            addCriterion("csm_family not between", value1, value2, "csmFamily");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameIsNull() {
            addCriterion("csm_username is null");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameIsNotNull() {
            addCriterion("csm_username is not null");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameEqualTo(String value) {
            addCriterion("csm_username =", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameNotEqualTo(String value) {
            addCriterion("csm_username <>", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameGreaterThan(String value) {
            addCriterion("csm_username >", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("csm_username >=", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameLessThan(String value) {
            addCriterion("csm_username <", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameLessThanOrEqualTo(String value) {
            addCriterion("csm_username <=", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameLike(String value) {
            addCriterion("csm_username like", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameNotLike(String value) {
            addCriterion("csm_username not like", value, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameIn(List<String> values) {
            addCriterion("csm_username in", values, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameNotIn(List<String> values) {
            addCriterion("csm_username not in", values, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameBetween(String value1, String value2) {
            addCriterion("csm_username between", value1, value2, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmUsernameNotBetween(String value1, String value2) {
            addCriterion("csm_username not between", value1, value2, "csmUsername");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordIsNull() {
            addCriterion("csm_password is null");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordIsNotNull() {
            addCriterion("csm_password is not null");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordEqualTo(String value) {
            addCriterion("csm_password =", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordNotEqualTo(String value) {
            addCriterion("csm_password <>", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordGreaterThan(String value) {
            addCriterion("csm_password >", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("csm_password >=", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordLessThan(String value) {
            addCriterion("csm_password <", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordLessThanOrEqualTo(String value) {
            addCriterion("csm_password <=", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordLike(String value) {
            addCriterion("csm_password like", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordNotLike(String value) {
            addCriterion("csm_password not like", value, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordIn(List<String> values) {
            addCriterion("csm_password in", values, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordNotIn(List<String> values) {
            addCriterion("csm_password not in", values, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordBetween(String value1, String value2) {
            addCriterion("csm_password between", value1, value2, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmPasswordNotBetween(String value1, String value2) {
            addCriterion("csm_password not between", value1, value2, "csmPassword");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsIsNull() {
            addCriterion("csm_projects is null");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsIsNotNull() {
            addCriterion("csm_projects is not null");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsEqualTo(String value) {
            addCriterion("csm_projects =", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsNotEqualTo(String value) {
            addCriterion("csm_projects <>", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsGreaterThan(String value) {
            addCriterion("csm_projects >", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsGreaterThanOrEqualTo(String value) {
            addCriterion("csm_projects >=", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsLessThan(String value) {
            addCriterion("csm_projects <", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsLessThanOrEqualTo(String value) {
            addCriterion("csm_projects <=", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsLike(String value) {
            addCriterion("csm_projects like", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsNotLike(String value) {
            addCriterion("csm_projects not like", value, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsIn(List<String> values) {
            addCriterion("csm_projects in", values, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsNotIn(List<String> values) {
            addCriterion("csm_projects not in", values, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsBetween(String value1, String value2) {
            addCriterion("csm_projects between", value1, value2, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmProjectsNotBetween(String value1, String value2) {
            addCriterion("csm_projects not between", value1, value2, "csmProjects");
            return (Criteria) this;
        }

        public Criteria andCsmPositionIsNull() {
            addCriterion("csm_position is null");
            return (Criteria) this;
        }

        public Criteria andCsmPositionIsNotNull() {
            addCriterion("csm_position is not null");
            return (Criteria) this;
        }

        public Criteria andCsmPositionEqualTo(String value) {
            addCriterion("csm_position =", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionNotEqualTo(String value) {
            addCriterion("csm_position <>", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionGreaterThan(String value) {
            addCriterion("csm_position >", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionGreaterThanOrEqualTo(String value) {
            addCriterion("csm_position >=", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionLessThan(String value) {
            addCriterion("csm_position <", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionLessThanOrEqualTo(String value) {
            addCriterion("csm_position <=", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionLike(String value) {
            addCriterion("csm_position like", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionNotLike(String value) {
            addCriterion("csm_position not like", value, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionIn(List<String> values) {
            addCriterion("csm_position in", values, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionNotIn(List<String> values) {
            addCriterion("csm_position not in", values, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionBetween(String value1, String value2) {
            addCriterion("csm_position between", value1, value2, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmPositionNotBetween(String value1, String value2) {
            addCriterion("csm_position not between", value1, value2, "csmPosition");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersIsNull() {
            addCriterion("csm_numbers is null");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersIsNotNull() {
            addCriterion("csm_numbers is not null");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersEqualTo(String value) {
            addCriterion("csm_numbers =", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersNotEqualTo(String value) {
            addCriterion("csm_numbers <>", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersGreaterThan(String value) {
            addCriterion("csm_numbers >", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersGreaterThanOrEqualTo(String value) {
            addCriterion("csm_numbers >=", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersLessThan(String value) {
            addCriterion("csm_numbers <", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersLessThanOrEqualTo(String value) {
            addCriterion("csm_numbers <=", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersLike(String value) {
            addCriterion("csm_numbers like", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersNotLike(String value) {
            addCriterion("csm_numbers not like", value, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersIn(List<String> values) {
            addCriterion("csm_numbers in", values, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersNotIn(List<String> values) {
            addCriterion("csm_numbers not in", values, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersBetween(String value1, String value2) {
            addCriterion("csm_numbers between", value1, value2, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmNumbersNotBetween(String value1, String value2) {
            addCriterion("csm_numbers not between", value1, value2, "csmNumbers");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalIsNull() {
            addCriterion("csm_interval is null");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalIsNotNull() {
            addCriterion("csm_interval is not null");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalEqualTo(Long value) {
            addCriterion("csm_interval =", value, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalNotEqualTo(Long value) {
            addCriterion("csm_interval <>", value, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalGreaterThan(Long value) {
            addCriterion("csm_interval >", value, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalGreaterThanOrEqualTo(Long value) {
            addCriterion("csm_interval >=", value, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalLessThan(Long value) {
            addCriterion("csm_interval <", value, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalLessThanOrEqualTo(Long value) {
            addCriterion("csm_interval <=", value, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalIn(List<Long> values) {
            addCriterion("csm_interval in", values, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalNotIn(List<Long> values) {
            addCriterion("csm_interval not in", values, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalBetween(Long value1, Long value2) {
            addCriterion("csm_interval between", value1, value2, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmIntervalNotBetween(Long value1, Long value2) {
            addCriterion("csm_interval not between", value1, value2, "csmInterval");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeIsNull() {
            addCriterion("csm_update_time is null");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeIsNotNull() {
            addCriterion("csm_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeEqualTo(Date value) {
            addCriterion("csm_update_time =", value, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeNotEqualTo(Date value) {
            addCriterion("csm_update_time <>", value, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeGreaterThan(Date value) {
            addCriterion("csm_update_time >", value, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("csm_update_time >=", value, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeLessThan(Date value) {
            addCriterion("csm_update_time <", value, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("csm_update_time <=", value, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeIn(List<Date> values) {
            addCriterion("csm_update_time in", values, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeNotIn(List<Date> values) {
            addCriterion("csm_update_time not in", values, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("csm_update_time between", value1, value2, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("csm_update_time not between", value1, value2, "csmUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeIsNull() {
            addCriterion("csm_add_time is null");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeIsNotNull() {
            addCriterion("csm_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeEqualTo(Date value) {
            addCriterion("csm_add_time =", value, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeNotEqualTo(Date value) {
            addCriterion("csm_add_time <>", value, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeGreaterThan(Date value) {
            addCriterion("csm_add_time >", value, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("csm_add_time >=", value, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeLessThan(Date value) {
            addCriterion("csm_add_time <", value, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("csm_add_time <=", value, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeIn(List<Date> values) {
            addCriterion("csm_add_time in", values, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeNotIn(List<Date> values) {
            addCriterion("csm_add_time not in", values, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeBetween(Date value1, Date value2) {
            addCriterion("csm_add_time between", value1, value2, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("csm_add_time not between", value1, value2, "csmAddTime");
            return (Criteria) this;
        }

        public Criteria andCsmStatusIsNull() {
            addCriterion("csm_status is null");
            return (Criteria) this;
        }

        public Criteria andCsmStatusIsNotNull() {
            addCriterion("csm_status is not null");
            return (Criteria) this;
        }

        public Criteria andCsmStatusEqualTo(Short value) {
            addCriterion("csm_status =", value, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusNotEqualTo(Short value) {
            addCriterion("csm_status <>", value, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusGreaterThan(Short value) {
            addCriterion("csm_status >", value, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("csm_status >=", value, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusLessThan(Short value) {
            addCriterion("csm_status <", value, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusLessThanOrEqualTo(Short value) {
            addCriterion("csm_status <=", value, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusIn(List<Short> values) {
            addCriterion("csm_status in", values, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusNotIn(List<Short> values) {
            addCriterion("csm_status not in", values, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusBetween(Short value1, Short value2) {
            addCriterion("csm_status between", value1, value2, "csmStatus");
            return (Criteria) this;
        }

        public Criteria andCsmStatusNotBetween(Short value1, Short value2) {
            addCriterion("csm_status not between", value1, value2, "csmStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_manage
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_manage
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}