package com.ccclubs.pub.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CsPaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public CsPaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCshsNumberIsNull() {
            addCriterion("cshs_number is null");
            return (Criteria) this;
        }

        public Criteria andCshsNumberIsNotNull() {
            addCriterion("cshs_number is not null");
            return (Criteria) this;
        }

        public Criteria andCshsNumberEqualTo(String value) {
            addCriterion("cshs_number =", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberNotEqualTo(String value) {
            addCriterion("cshs_number <>", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberGreaterThan(String value) {
            addCriterion("cshs_number >", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberGreaterThanOrEqualTo(String value) {
            addCriterion("cshs_number >=", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberLessThan(String value) {
            addCriterion("cshs_number <", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberLessThanOrEqualTo(String value) {
            addCriterion("cshs_number <=", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberLike(String value) {
            addCriterion("cshs_number like", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberNotLike(String value) {
            addCriterion("cshs_number not like", value, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberIn(List<String> values) {
            addCriterion("cshs_number in", values, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberNotIn(List<String> values) {
            addCriterion("cshs_number not in", values, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberBetween(String value1, String value2) {
            addCriterion("cshs_number between", value1, value2, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsNumberNotBetween(String value1, String value2) {
            addCriterion("cshs_number not between", value1, value2, "cshsNumber");
            return (Criteria) this;
        }

        public Criteria andCshsAccessIsNull() {
            addCriterion("cshs_access is null");
            return (Criteria) this;
        }

        public Criteria andCshsAccessIsNotNull() {
            addCriterion("cshs_access is not null");
            return (Criteria) this;
        }

        public Criteria andCshsAccessEqualTo(Byte value) {
            addCriterion("cshs_access =", value, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessNotEqualTo(Byte value) {
            addCriterion("cshs_access <>", value, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessGreaterThan(Byte value) {
            addCriterion("cshs_access >", value, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessGreaterThanOrEqualTo(Byte value) {
            addCriterion("cshs_access >=", value, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessLessThan(Byte value) {
            addCriterion("cshs_access <", value, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessLessThanOrEqualTo(Byte value) {
            addCriterion("cshs_access <=", value, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessIn(List<Byte> values) {
            addCriterion("cshs_access in", values, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessNotIn(List<Byte> values) {
            addCriterion("cshs_access not in", values, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessBetween(Byte value1, Byte value2) {
            addCriterion("cshs_access between", value1, value2, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andCshsAccessNotBetween(Byte value1, Byte value2) {
            addCriterion("cshs_access not between", value1, value2, "cshsAccess");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsIsNull() {
            addCriterion("start_state_mills is null");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsIsNotNull() {
            addCriterion("start_state_mills is not null");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsEqualTo(Long value) {
            addCriterion("start_state_mills =", value, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsNotEqualTo(Long value) {
            addCriterion("start_state_mills <>", value, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsGreaterThan(Long value) {
            addCriterion("start_state_mills >", value, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsGreaterThanOrEqualTo(Long value) {
            addCriterion("start_state_mills >=", value, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsLessThan(Long value) {
            addCriterion("start_state_mills <", value, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsLessThanOrEqualTo(Long value) {
            addCriterion("start_state_mills <=", value, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsIn(List<Long> values) {
            addCriterion("start_state_mills in", values, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsNotIn(List<Long> values) {
            addCriterion("start_state_mills not in", values, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsBetween(Long value1, Long value2) {
            addCriterion("start_state_mills between", value1, value2, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andStartStateMillsNotBetween(Long value1, Long value2) {
            addCriterion("start_state_mills not between", value1, value2, "startStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsIsNull() {
            addCriterion("end_state_mills is null");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsIsNotNull() {
            addCriterion("end_state_mills is not null");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsEqualTo(Long value) {
            addCriterion("end_state_mills =", value, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsNotEqualTo(Long value) {
            addCriterion("end_state_mills <>", value, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsGreaterThan(Long value) {
            addCriterion("end_state_mills >", value, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsGreaterThanOrEqualTo(Long value) {
            addCriterion("end_state_mills >=", value, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsLessThan(Long value) {
            addCriterion("end_state_mills <", value, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsLessThanOrEqualTo(Long value) {
            addCriterion("end_state_mills <=", value, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsIn(List<Long> values) {
            addCriterion("end_state_mills in", values, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsNotIn(List<Long> values) {
            addCriterion("end_state_mills not in", values, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsBetween(Long value1, Long value2) {
            addCriterion("end_state_mills between", value1, value2, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andEndStateMillsNotBetween(Long value1, Long value2) {
            addCriterion("end_state_mills not between", value1, value2, "endStateMills");
            return (Criteria) this;
        }

        public Criteria andStateYearIsNull() {
            addCriterion("state_year is null");
            return (Criteria) this;
        }

        public Criteria andStateYearIsNotNull() {
            addCriterion("state_year is not null");
            return (Criteria) this;
        }

        public Criteria andStateYearEqualTo(Integer value) {
            addCriterion("state_year =", value, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearNotEqualTo(Integer value) {
            addCriterion("state_year <>", value, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearGreaterThan(Integer value) {
            addCriterion("state_year >", value, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("state_year >=", value, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearLessThan(Integer value) {
            addCriterion("state_year <", value, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearLessThanOrEqualTo(Integer value) {
            addCriterion("state_year <=", value, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearIn(List<Integer> values) {
            addCriterion("state_year in", values, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearNotIn(List<Integer> values) {
            addCriterion("state_year not in", values, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearBetween(Integer value1, Integer value2) {
            addCriterion("state_year between", value1, value2, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateYearNotBetween(Integer value1, Integer value2) {
            addCriterion("state_year not between", value1, value2, "stateYear");
            return (Criteria) this;
        }

        public Criteria andStateMonthIsNull() {
            addCriterion("state_month is null");
            return (Criteria) this;
        }

        public Criteria andStateMonthIsNotNull() {
            addCriterion("state_month is not null");
            return (Criteria) this;
        }

        public Criteria andStateMonthEqualTo(Integer value) {
            addCriterion("state_month =", value, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthNotEqualTo(Integer value) {
            addCriterion("state_month <>", value, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthGreaterThan(Integer value) {
            addCriterion("state_month >", value, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("state_month >=", value, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthLessThan(Integer value) {
            addCriterion("state_month <", value, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthLessThanOrEqualTo(Integer value) {
            addCriterion("state_month <=", value, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthIn(List<Integer> values) {
            addCriterion("state_month in", values, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthNotIn(List<Integer> values) {
            addCriterion("state_month not in", values, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthBetween(Integer value1, Integer value2) {
            addCriterion("state_month between", value1, value2, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("state_month not between", value1, value2, "stateMonth");
            return (Criteria) this;
        }

        public Criteria andStateTypeIsNull() {
            addCriterion("state_type is null");
            return (Criteria) this;
        }

        public Criteria andStateTypeIsNotNull() {
            addCriterion("state_type is not null");
            return (Criteria) this;
        }

        public Criteria andStateTypeEqualTo(Byte value) {
            addCriterion("state_type =", value, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeNotEqualTo(Byte value) {
            addCriterion("state_type <>", value, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeGreaterThan(Byte value) {
            addCriterion("state_type >", value, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("state_type >=", value, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeLessThan(Byte value) {
            addCriterion("state_type <", value, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeLessThanOrEqualTo(Byte value) {
            addCriterion("state_type <=", value, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeIn(List<Byte> values) {
            addCriterion("state_type in", values, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeNotIn(List<Byte> values) {
            addCriterion("state_type not in", values, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeBetween(Byte value1, Byte value2) {
            addCriterion("state_type between", value1, value2, "stateType");
            return (Criteria) this;
        }

        public Criteria andStateTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("state_type not between", value1, value2, "stateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeIsNull() {
            addCriterion("sub_state_type is null");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeIsNotNull() {
            addCriterion("sub_state_type is not null");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeEqualTo(Byte value) {
            addCriterion("sub_state_type =", value, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeNotEqualTo(Byte value) {
            addCriterion("sub_state_type <>", value, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeGreaterThan(Byte value) {
            addCriterion("sub_state_type >", value, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("sub_state_type >=", value, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeLessThan(Byte value) {
            addCriterion("sub_state_type <", value, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeLessThanOrEqualTo(Byte value) {
            addCriterion("sub_state_type <=", value, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeIn(List<Byte> values) {
            addCriterion("sub_state_type in", values, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeNotIn(List<Byte> values) {
            addCriterion("sub_state_type not in", values, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeBetween(Byte value1, Byte value2) {
            addCriterion("sub_state_type between", value1, value2, "subStateType");
            return (Criteria) this;
        }

        public Criteria andSubStateTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("sub_state_type not between", value1, value2, "subStateType");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryIsNull() {
            addCriterion("start_state_battery is null");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryIsNotNull() {
            addCriterion("start_state_battery is not null");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryEqualTo(Short value) {
            addCriterion("start_state_battery =", value, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryNotEqualTo(Short value) {
            addCriterion("start_state_battery <>", value, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryGreaterThan(Short value) {
            addCriterion("start_state_battery >", value, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryGreaterThanOrEqualTo(Short value) {
            addCriterion("start_state_battery >=", value, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryLessThan(Short value) {
            addCriterion("start_state_battery <", value, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryLessThanOrEqualTo(Short value) {
            addCriterion("start_state_battery <=", value, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryIn(List<Short> values) {
            addCriterion("start_state_battery in", values, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryNotIn(List<Short> values) {
            addCriterion("start_state_battery not in", values, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryBetween(Short value1, Short value2) {
            addCriterion("start_state_battery between", value1, value2, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andStartStateBatteryNotBetween(Short value1, Short value2) {
            addCriterion("start_state_battery not between", value1, value2, "startStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryIsNull() {
            addCriterion("end_state_battery is null");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryIsNotNull() {
            addCriterion("end_state_battery is not null");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryEqualTo(Short value) {
            addCriterion("end_state_battery =", value, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryNotEqualTo(Short value) {
            addCriterion("end_state_battery <>", value, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryGreaterThan(Short value) {
            addCriterion("end_state_battery >", value, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryGreaterThanOrEqualTo(Short value) {
            addCriterion("end_state_battery >=", value, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryLessThan(Short value) {
            addCriterion("end_state_battery <", value, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryLessThanOrEqualTo(Short value) {
            addCriterion("end_state_battery <=", value, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryIn(List<Short> values) {
            addCriterion("end_state_battery in", values, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryNotIn(List<Short> values) {
            addCriterion("end_state_battery not in", values, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryBetween(Short value1, Short value2) {
            addCriterion("end_state_battery between", value1, value2, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andEndStateBatteryNotBetween(Short value1, Short value2) {
            addCriterion("end_state_battery not between", value1, value2, "endStateBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryIsNull() {
            addCriterion("changed_battery is null");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryIsNotNull() {
            addCriterion("changed_battery is not null");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryEqualTo(Short value) {
            addCriterion("changed_battery =", value, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryNotEqualTo(Short value) {
            addCriterion("changed_battery <>", value, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryGreaterThan(Short value) {
            addCriterion("changed_battery >", value, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryGreaterThanOrEqualTo(Short value) {
            addCriterion("changed_battery >=", value, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryLessThan(Short value) {
            addCriterion("changed_battery <", value, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryLessThanOrEqualTo(Short value) {
            addCriterion("changed_battery <=", value, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryIn(List<Short> values) {
            addCriterion("changed_battery in", values, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryNotIn(List<Short> values) {
            addCriterion("changed_battery not in", values, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryBetween(Short value1, Short value2) {
            addCriterion("changed_battery between", value1, value2, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andChangedBatteryNotBetween(Short value1, Short value2) {
            addCriterion("changed_battery not between", value1, value2, "changedBattery");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesIsNull() {
            addCriterion("start_obd_miles is null");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesIsNotNull() {
            addCriterion("start_obd_miles is not null");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesEqualTo(Integer value) {
            addCriterion("start_obd_miles =", value, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesNotEqualTo(Integer value) {
            addCriterion("start_obd_miles <>", value, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesGreaterThan(Integer value) {
            addCriterion("start_obd_miles >", value, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesGreaterThanOrEqualTo(Integer value) {
            addCriterion("start_obd_miles >=", value, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesLessThan(Integer value) {
            addCriterion("start_obd_miles <", value, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesLessThanOrEqualTo(Integer value) {
            addCriterion("start_obd_miles <=", value, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesIn(List<Integer> values) {
            addCriterion("start_obd_miles in", values, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesNotIn(List<Integer> values) {
            addCriterion("start_obd_miles not in", values, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesBetween(Integer value1, Integer value2) {
            addCriterion("start_obd_miles between", value1, value2, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andStartObdMilesNotBetween(Integer value1, Integer value2) {
            addCriterion("start_obd_miles not between", value1, value2, "startObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesIsNull() {
            addCriterion("end_obd_miles is null");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesIsNotNull() {
            addCriterion("end_obd_miles is not null");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesEqualTo(Integer value) {
            addCriterion("end_obd_miles =", value, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesNotEqualTo(Integer value) {
            addCriterion("end_obd_miles <>", value, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesGreaterThan(Integer value) {
            addCriterion("end_obd_miles >", value, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_obd_miles >=", value, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesLessThan(Integer value) {
            addCriterion("end_obd_miles <", value, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesLessThanOrEqualTo(Integer value) {
            addCriterion("end_obd_miles <=", value, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesIn(List<Integer> values) {
            addCriterion("end_obd_miles in", values, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesNotIn(List<Integer> values) {
            addCriterion("end_obd_miles not in", values, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesBetween(Integer value1, Integer value2) {
            addCriterion("end_obd_miles between", value1, value2, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andEndObdMilesNotBetween(Integer value1, Integer value2) {
            addCriterion("end_obd_miles not between", value1, value2, "endObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesIsNull() {
            addCriterion("changed_obd_miles is null");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesIsNotNull() {
            addCriterion("changed_obd_miles is not null");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesEqualTo(Integer value) {
            addCriterion("changed_obd_miles =", value, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesNotEqualTo(Integer value) {
            addCriterion("changed_obd_miles <>", value, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesGreaterThan(Integer value) {
            addCriterion("changed_obd_miles >", value, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesGreaterThanOrEqualTo(Integer value) {
            addCriterion("changed_obd_miles >=", value, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesLessThan(Integer value) {
            addCriterion("changed_obd_miles <", value, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesLessThanOrEqualTo(Integer value) {
            addCriterion("changed_obd_miles <=", value, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesIn(List<Integer> values) {
            addCriterion("changed_obd_miles in", values, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesNotIn(List<Integer> values) {
            addCriterion("changed_obd_miles not in", values, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesBetween(Integer value1, Integer value2) {
            addCriterion("changed_obd_miles between", value1, value2, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andChangedObdMilesNotBetween(Integer value1, Integer value2) {
            addCriterion("changed_obd_miles not between", value1, value2, "changedObdMiles");
            return (Criteria) this;
        }

        public Criteria andActiveFlgIsNull() {
            addCriterion("active_flg is null");
            return (Criteria) this;
        }

        public Criteria andActiveFlgIsNotNull() {
            addCriterion("active_flg is not null");
            return (Criteria) this;
        }

        public Criteria andActiveFlgEqualTo(Byte value) {
            addCriterion("active_flg =", value, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgNotEqualTo(Byte value) {
            addCriterion("active_flg <>", value, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgGreaterThan(Byte value) {
            addCriterion("active_flg >", value, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgGreaterThanOrEqualTo(Byte value) {
            addCriterion("active_flg >=", value, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgLessThan(Byte value) {
            addCriterion("active_flg <", value, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgLessThanOrEqualTo(Byte value) {
            addCriterion("active_flg <=", value, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgIn(List<Byte> values) {
            addCriterion("active_flg in", values, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgNotIn(List<Byte> values) {
            addCriterion("active_flg not in", values, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgBetween(Byte value1, Byte value2) {
            addCriterion("active_flg between", value1, value2, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andActiveFlgNotBetween(Byte value1, Byte value2) {
            addCriterion("active_flg not between", value1, value2, "activeFlg");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_pace
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_pace
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}