package com.ccclubs.pub.orm.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table srv_attribute
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SrvAttribute implements Serializable {
    /**
     * Database Column Remarks:
     *   编号:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_id
     *
     * @mbg.generated
     */
    private Long saId;

    /**
     * Database Column Remarks:
     *   子域:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_host
     *
     * @mbg.generated
     */
    private Long saHost;

    /**
     * Database Column Remarks:
     *   类型:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_parent
     *
     * @mbg.generated
     */
    private Long saParent;

    /**
     * Database Column Remarks:
     *   名称:属性名称，如html中select的option的text内容;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_name
     *
     * @mbg.generated
     */
    private String saName;

    /**
     * Database Column Remarks:
     *   标识:程序变量命名规则格式;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_flag
     *
     * @mbg.generated
     */
    private String saFlag;

    /**
     * Database Column Remarks:
     *   数据:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_data
     *
     * @mbg.generated
     */
    private String saData;

    /**
     * Database Column Remarks:
     *   状态:1:有效,0:内容;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srv_attribute.sa_status
     *
     * @mbg.generated
     */
    private Short saStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table srv_attribute
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_id
     *
     * @return the value of srv_attribute.sa_id
     *
     * @mbg.generated
     */
    public Long getSaId() {
        return saId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_id
     *
     * @param saId the value for srv_attribute.sa_id
     *
     * @mbg.generated
     */
    public void setSaId(Long saId) {
        this.saId = saId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_host
     *
     * @return the value of srv_attribute.sa_host
     *
     * @mbg.generated
     */
    public Long getSaHost() {
        return saHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_host
     *
     * @param saHost the value for srv_attribute.sa_host
     *
     * @mbg.generated
     */
    public void setSaHost(Long saHost) {
        this.saHost = saHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_parent
     *
     * @return the value of srv_attribute.sa_parent
     *
     * @mbg.generated
     */
    public Long getSaParent() {
        return saParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_parent
     *
     * @param saParent the value for srv_attribute.sa_parent
     *
     * @mbg.generated
     */
    public void setSaParent(Long saParent) {
        this.saParent = saParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_name
     *
     * @return the value of srv_attribute.sa_name
     *
     * @mbg.generated
     */
    public String getSaName() {
        return saName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_name
     *
     * @param saName the value for srv_attribute.sa_name
     *
     * @mbg.generated
     */
    public void setSaName(String saName) {
        this.saName = saName == null ? null : saName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_flag
     *
     * @return the value of srv_attribute.sa_flag
     *
     * @mbg.generated
     */
    public String getSaFlag() {
        return saFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_flag
     *
     * @param saFlag the value for srv_attribute.sa_flag
     *
     * @mbg.generated
     */
    public void setSaFlag(String saFlag) {
        this.saFlag = saFlag == null ? null : saFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_data
     *
     * @return the value of srv_attribute.sa_data
     *
     * @mbg.generated
     */
    public String getSaData() {
        return saData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_data
     *
     * @param saData the value for srv_attribute.sa_data
     *
     * @mbg.generated
     */
    public void setSaData(String saData) {
        this.saData = saData == null ? null : saData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srv_attribute.sa_status
     *
     * @return the value of srv_attribute.sa_status
     *
     * @mbg.generated
     */
    public Short getSaStatus() {
        return saStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srv_attribute.sa_status
     *
     * @param saStatus the value for srv_attribute.sa_status
     *
     * @mbg.generated
     */
    public void setSaStatus(Short saStatus) {
        this.saStatus = saStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_attribute
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SrvAttribute other = (SrvAttribute) that;
        return (this.getSaId() == null ? other.getSaId() == null : this.getSaId().equals(other.getSaId()))
            && (this.getSaHost() == null ? other.getSaHost() == null : this.getSaHost().equals(other.getSaHost()))
            && (this.getSaParent() == null ? other.getSaParent() == null : this.getSaParent().equals(other.getSaParent()))
            && (this.getSaName() == null ? other.getSaName() == null : this.getSaName().equals(other.getSaName()))
            && (this.getSaFlag() == null ? other.getSaFlag() == null : this.getSaFlag().equals(other.getSaFlag()))
            && (this.getSaData() == null ? other.getSaData() == null : this.getSaData().equals(other.getSaData()))
            && (this.getSaStatus() == null ? other.getSaStatus() == null : this.getSaStatus().equals(other.getSaStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_attribute
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSaId() == null) ? 0 : getSaId().hashCode());
        result = prime * result + ((getSaHost() == null) ? 0 : getSaHost().hashCode());
        result = prime * result + ((getSaParent() == null) ? 0 : getSaParent().hashCode());
        result = prime * result + ((getSaName() == null) ? 0 : getSaName().hashCode());
        result = prime * result + ((getSaFlag() == null) ? 0 : getSaFlag().hashCode());
        result = prime * result + ((getSaData() == null) ? 0 : getSaData().hashCode());
        result = prime * result + ((getSaStatus() == null) ? 0 : getSaStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srv_attribute
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", saId=").append(saId);
        sb.append(", saHost=").append(saHost);
        sb.append(", saParent=").append(saParent);
        sb.append(", saName=").append(saName);
        sb.append(", saFlag=").append(saFlag);
        sb.append(", saData=").append(saData);
        sb.append(", saStatus=").append(saStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}