package com.ccclubs.pub.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbUpgradeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public TbUpgradeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTbuIdIsNull() {
            addCriterion("tbu_id is null");
            return (Criteria) this;
        }

        public Criteria andTbuIdIsNotNull() {
            addCriterion("tbu_id is not null");
            return (Criteria) this;
        }

        public Criteria andTbuIdEqualTo(Long value) {
            addCriterion("tbu_id =", value, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdNotEqualTo(Long value) {
            addCriterion("tbu_id <>", value, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdGreaterThan(Long value) {
            addCriterion("tbu_id >", value, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tbu_id >=", value, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdLessThan(Long value) {
            addCriterion("tbu_id <", value, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdLessThanOrEqualTo(Long value) {
            addCriterion("tbu_id <=", value, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdIn(List<Long> values) {
            addCriterion("tbu_id in", values, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdNotIn(List<Long> values) {
            addCriterion("tbu_id not in", values, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdBetween(Long value1, Long value2) {
            addCriterion("tbu_id between", value1, value2, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuIdNotBetween(Long value1, Long value2) {
            addCriterion("tbu_id not between", value1, value2, "tbuId");
            return (Criteria) this;
        }

        public Criteria andTbuMachineIsNull() {
            addCriterion("tbu_machine is null");
            return (Criteria) this;
        }

        public Criteria andTbuMachineIsNotNull() {
            addCriterion("tbu_machine is not null");
            return (Criteria) this;
        }

        public Criteria andTbuMachineEqualTo(Long value) {
            addCriterion("tbu_machine =", value, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineNotEqualTo(Long value) {
            addCriterion("tbu_machine <>", value, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineGreaterThan(Long value) {
            addCriterion("tbu_machine >", value, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineGreaterThanOrEqualTo(Long value) {
            addCriterion("tbu_machine >=", value, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineLessThan(Long value) {
            addCriterion("tbu_machine <", value, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineLessThanOrEqualTo(Long value) {
            addCriterion("tbu_machine <=", value, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineIn(List<Long> values) {
            addCriterion("tbu_machine in", values, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineNotIn(List<Long> values) {
            addCriterion("tbu_machine not in", values, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineBetween(Long value1, Long value2) {
            addCriterion("tbu_machine between", value1, value2, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuMachineNotBetween(Long value1, Long value2) {
            addCriterion("tbu_machine not between", value1, value2, "tbuMachine");
            return (Criteria) this;
        }

        public Criteria andTbuNumberIsNull() {
            addCriterion("tbu_number is null");
            return (Criteria) this;
        }

        public Criteria andTbuNumberIsNotNull() {
            addCriterion("tbu_number is not null");
            return (Criteria) this;
        }

        public Criteria andTbuNumberEqualTo(String value) {
            addCriterion("tbu_number =", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberNotEqualTo(String value) {
            addCriterion("tbu_number <>", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberGreaterThan(String value) {
            addCriterion("tbu_number >", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberGreaterThanOrEqualTo(String value) {
            addCriterion("tbu_number >=", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberLessThan(String value) {
            addCriterion("tbu_number <", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberLessThanOrEqualTo(String value) {
            addCriterion("tbu_number <=", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberLike(String value) {
            addCriterion("tbu_number like", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberNotLike(String value) {
            addCriterion("tbu_number not like", value, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberIn(List<String> values) {
            addCriterion("tbu_number in", values, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberNotIn(List<String> values) {
            addCriterion("tbu_number not in", values, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberBetween(String value1, String value2) {
            addCriterion("tbu_number between", value1, value2, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuNumberNotBetween(String value1, String value2) {
            addCriterion("tbu_number not between", value1, value2, "tbuNumber");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoIsNull() {
            addCriterion("tbu_sim_no is null");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoIsNotNull() {
            addCriterion("tbu_sim_no is not null");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoEqualTo(String value) {
            addCriterion("tbu_sim_no =", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoNotEqualTo(String value) {
            addCriterion("tbu_sim_no <>", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoGreaterThan(String value) {
            addCriterion("tbu_sim_no >", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoGreaterThanOrEqualTo(String value) {
            addCriterion("tbu_sim_no >=", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoLessThan(String value) {
            addCriterion("tbu_sim_no <", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoLessThanOrEqualTo(String value) {
            addCriterion("tbu_sim_no <=", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoLike(String value) {
            addCriterion("tbu_sim_no like", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoNotLike(String value) {
            addCriterion("tbu_sim_no not like", value, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoIn(List<String> values) {
            addCriterion("tbu_sim_no in", values, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoNotIn(List<String> values) {
            addCriterion("tbu_sim_no not in", values, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoBetween(String value1, String value2) {
            addCriterion("tbu_sim_no between", value1, value2, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuSimNoNotBetween(String value1, String value2) {
            addCriterion("tbu_sim_no not between", value1, value2, "tbuSimNo");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeIsNull() {
            addCriterion("tbu_te_type is null");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeIsNotNull() {
            addCriterion("tbu_te_type is not null");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeEqualTo(Short value) {
            addCriterion("tbu_te_type =", value, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeNotEqualTo(Short value) {
            addCriterion("tbu_te_type <>", value, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeGreaterThan(Short value) {
            addCriterion("tbu_te_type >", value, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("tbu_te_type >=", value, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeLessThan(Short value) {
            addCriterion("tbu_te_type <", value, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeLessThanOrEqualTo(Short value) {
            addCriterion("tbu_te_type <=", value, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeIn(List<Short> values) {
            addCriterion("tbu_te_type in", values, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeNotIn(List<Short> values) {
            addCriterion("tbu_te_type not in", values, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeBetween(Short value1, Short value2) {
            addCriterion("tbu_te_type between", value1, value2, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuTeTypeNotBetween(Short value1, Short value2) {
            addCriterion("tbu_te_type not between", value1, value2, "tbuTeType");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolIsNull() {
            addCriterion("tbu_protocol is null");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolIsNotNull() {
            addCriterion("tbu_protocol is not null");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolEqualTo(Short value) {
            addCriterion("tbu_protocol =", value, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolNotEqualTo(Short value) {
            addCriterion("tbu_protocol <>", value, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolGreaterThan(Short value) {
            addCriterion("tbu_protocol >", value, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolGreaterThanOrEqualTo(Short value) {
            addCriterion("tbu_protocol >=", value, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolLessThan(Short value) {
            addCriterion("tbu_protocol <", value, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolLessThanOrEqualTo(Short value) {
            addCriterion("tbu_protocol <=", value, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolIn(List<Short> values) {
            addCriterion("tbu_protocol in", values, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolNotIn(List<Short> values) {
            addCriterion("tbu_protocol not in", values, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolBetween(Short value1, Short value2) {
            addCriterion("tbu_protocol between", value1, value2, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuProtocolNotBetween(Short value1, Short value2) {
            addCriterion("tbu_protocol not between", value1, value2, "tbuProtocol");
            return (Criteria) this;
        }

        public Criteria andTbuFileIsNull() {
            addCriterion("tbu_file is null");
            return (Criteria) this;
        }

        public Criteria andTbuFileIsNotNull() {
            addCriterion("tbu_file is not null");
            return (Criteria) this;
        }

        public Criteria andTbuFileEqualTo(String value) {
            addCriterion("tbu_file =", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileNotEqualTo(String value) {
            addCriterion("tbu_file <>", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileGreaterThan(String value) {
            addCriterion("tbu_file >", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileGreaterThanOrEqualTo(String value) {
            addCriterion("tbu_file >=", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileLessThan(String value) {
            addCriterion("tbu_file <", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileLessThanOrEqualTo(String value) {
            addCriterion("tbu_file <=", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileLike(String value) {
            addCriterion("tbu_file like", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileNotLike(String value) {
            addCriterion("tbu_file not like", value, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileIn(List<String> values) {
            addCriterion("tbu_file in", values, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileNotIn(List<String> values) {
            addCriterion("tbu_file not in", values, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileBetween(String value1, String value2) {
            addCriterion("tbu_file between", value1, value2, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuFileNotBetween(String value1, String value2) {
            addCriterion("tbu_file not between", value1, value2, "tbuFile");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksIsNull() {
            addCriterion("tbu_remarks is null");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksIsNotNull() {
            addCriterion("tbu_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksEqualTo(String value) {
            addCriterion("tbu_remarks =", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksNotEqualTo(String value) {
            addCriterion("tbu_remarks <>", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksGreaterThan(String value) {
            addCriterion("tbu_remarks >", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("tbu_remarks >=", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksLessThan(String value) {
            addCriterion("tbu_remarks <", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksLessThanOrEqualTo(String value) {
            addCriterion("tbu_remarks <=", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksLike(String value) {
            addCriterion("tbu_remarks like", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksNotLike(String value) {
            addCriterion("tbu_remarks not like", value, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksIn(List<String> values) {
            addCriterion("tbu_remarks in", values, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksNotIn(List<String> values) {
            addCriterion("tbu_remarks not in", values, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksBetween(String value1, String value2) {
            addCriterion("tbu_remarks between", value1, value2, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuRemarksNotBetween(String value1, String value2) {
            addCriterion("tbu_remarks not between", value1, value2, "tbuRemarks");
            return (Criteria) this;
        }

        public Criteria andTbuEditorIsNull() {
            addCriterion("tbu_editor is null");
            return (Criteria) this;
        }

        public Criteria andTbuEditorIsNotNull() {
            addCriterion("tbu_editor is not null");
            return (Criteria) this;
        }

        public Criteria andTbuEditorEqualTo(Long value) {
            addCriterion("tbu_editor =", value, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorNotEqualTo(Long value) {
            addCriterion("tbu_editor <>", value, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorGreaterThan(Long value) {
            addCriterion("tbu_editor >", value, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorGreaterThanOrEqualTo(Long value) {
            addCriterion("tbu_editor >=", value, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorLessThan(Long value) {
            addCriterion("tbu_editor <", value, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorLessThanOrEqualTo(Long value) {
            addCriterion("tbu_editor <=", value, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorIn(List<Long> values) {
            addCriterion("tbu_editor in", values, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorNotIn(List<Long> values) {
            addCriterion("tbu_editor not in", values, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorBetween(Long value1, Long value2) {
            addCriterion("tbu_editor between", value1, value2, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuEditorNotBetween(Long value1, Long value2) {
            addCriterion("tbu_editor not between", value1, value2, "tbuEditor");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeIsNull() {
            addCriterion("tbu_update_time is null");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeIsNotNull() {
            addCriterion("tbu_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeEqualTo(Date value) {
            addCriterion("tbu_update_time =", value, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeNotEqualTo(Date value) {
            addCriterion("tbu_update_time <>", value, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeGreaterThan(Date value) {
            addCriterion("tbu_update_time >", value, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tbu_update_time >=", value, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeLessThan(Date value) {
            addCriterion("tbu_update_time <", value, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("tbu_update_time <=", value, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeIn(List<Date> values) {
            addCriterion("tbu_update_time in", values, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeNotIn(List<Date> values) {
            addCriterion("tbu_update_time not in", values, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("tbu_update_time between", value1, value2, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("tbu_update_time not between", value1, value2, "tbuUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeIsNull() {
            addCriterion("tbu_add_time is null");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeIsNotNull() {
            addCriterion("tbu_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeEqualTo(Date value) {
            addCriterion("tbu_add_time =", value, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeNotEqualTo(Date value) {
            addCriterion("tbu_add_time <>", value, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeGreaterThan(Date value) {
            addCriterion("tbu_add_time >", value, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tbu_add_time >=", value, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeLessThan(Date value) {
            addCriterion("tbu_add_time <", value, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("tbu_add_time <=", value, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeIn(List<Date> values) {
            addCriterion("tbu_add_time in", values, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeNotIn(List<Date> values) {
            addCriterion("tbu_add_time not in", values, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeBetween(Date value1, Date value2) {
            addCriterion("tbu_add_time between", value1, value2, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("tbu_add_time not between", value1, value2, "tbuAddTime");
            return (Criteria) this;
        }

        public Criteria andTbuStatusIsNull() {
            addCriterion("tbu_status is null");
            return (Criteria) this;
        }

        public Criteria andTbuStatusIsNotNull() {
            addCriterion("tbu_status is not null");
            return (Criteria) this;
        }

        public Criteria andTbuStatusEqualTo(Short value) {
            addCriterion("tbu_status =", value, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusNotEqualTo(Short value) {
            addCriterion("tbu_status <>", value, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusGreaterThan(Short value) {
            addCriterion("tbu_status >", value, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("tbu_status >=", value, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusLessThan(Short value) {
            addCriterion("tbu_status <", value, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusLessThanOrEqualTo(Short value) {
            addCriterion("tbu_status <=", value, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusIn(List<Short> values) {
            addCriterion("tbu_status in", values, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusNotIn(List<Short> values) {
            addCriterion("tbu_status not in", values, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusBetween(Short value1, Short value2) {
            addCriterion("tbu_status between", value1, value2, "tbuStatus");
            return (Criteria) this;
        }

        public Criteria andTbuStatusNotBetween(Short value1, Short value2) {
            addCriterion("tbu_status not between", value1, value2, "tbuStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_upgrade
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_upgrade
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}